
let companyNameAll = ["DANA GROUP",
"RADIANT PHARMACEUTICALS LIMITED",
"NORTH SOUTH UNIVERSITY (NSU)",
"Esquire Group",
"Esquire Electronics",
"Orion Group",
"Ascent Group",
"Popular Pharmaceuticals",
"BIRDEM",
"Keya Cosmetics Ltd",
"Dhaka National Medical College",
"Gulshan Club Limited",
"National Heart Foundation",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"Bangladesh Medical Studies & Research Institute (BMSRI)",
"Islami Bank Institute of Technology",
"Brac University",
"IIDFC",
"Bangladesh Water Development Board",
"IFIC Bank",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Kallol Group",
"Dhaka Club",
"Dhaka Chamber of Commerce & Industry",
"Siddheswari Girls College",
"Bangabandhu Sheikh Mujib Medical University",
"Bangladesh Institute of Bank Management",
"DOREEN GROUP",
"Islamic Relief",
"Tetrapak (BD) Ltd",
"Phillip Morris",
"PDS Multinational Group",
"PDS Multinational Group",
"Islamic University of Technology (IUT), Banlgadesh",
"The Alliance Française",
"High Commission of India",
"BSRM Group",
"BSRM Group",
"Sajida Foundation",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"ACI LTD",
"Flora Ltd",
"Mohammadi Group",
"Kazi Farms",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Nasir Group",
"Bangla TRAC",
"Aristopharma",
"Bengal Group",
"Power Grid Company of Bangladesh",
"Kabir Group of Industries (KSRM)",
"Kabir Group of Industries (KSRM)",
"Youngone Corporation",
"Youngone Corporation",
"Palli Karma Sahayak Foundation",
"Partex Group",
"Partex Group",
"Dhaka Power Distribution Company Ltd",
"Grameen",
"Grameen",
"Eastern Bank Limited",
"Eastern Bank Limited",
"PUBALI BANK LTD",
"UCBL",
"Mutual Trust Bank Limited",
"DHAKA BANK",
"NATIONAL BANK LIMITED",
"SOUTHEAST BANK LTD",
"Exim Bank Limited",
"One Bank Limited",
"Bangladesh Petroleum Corporation",
"Bangladesh Petroleum Corporation",
"JAMUNA BANK LIMITED",
"BANGLADESH COMMERCE BANK",
"Mir Group of Companies",
"Homebound Packers and Shippers Ltd",
"ISLAMI BANK BANGLADESH LIMITED",
"ISLAMI BANK BANGLADESH LIMITED",
"SHAHJALAL ISLAMI BANK LIMITED",
"PACIFIC ZIPPER BANGLADESH LTD",
"RAK Group",
"RAK Group",
"RAK Group",
"RAK Group",
"RAK Group",
"Commercial Bank of Ceylon",
"HSBC",
"Citibank NA",
"Mitsubishi Corporation",
"German Red Cross",
"ABF Investments PLC",
"Youngone Corporation",
"Youngone Corporation",
"Youngone Corporation",
"Youngone Corporation",
"CapitaLand Development Ltd",
"Ispahani Islamia Eye Institute and Hospital",
"Edison group",
"Edison group",
"Edison group",
"Daffodil Group",
"Rupali Bank",
"Bangladesh-Malaysia Chamber of Commerce and Industry (BMCCI)",
"Total Transportation Ltd – CSCL",
"Bangladesh Foreign Trade Institute",
"National Housing Finance and Investment Limited",
"Islamic Finance and Investment Ltd",
"Shaheed Ramizuddin Cantonment College",
"National Finance Limited",
"Bangladesh University",
"Dhaka Cantt Girl's Public School and College",
"BEPZA",
"DUTCH BANGLA BANK LIMITED (DBBL)",
"South Bangla Agriculture & Commerce Bank Ltd",
"Islamic Development Bank –BISEW",
"NRB Bank",
"Union Bank",
"NRB Commercial Bank Limited",
"GLOBAL ISLAMI BANK",
"Karmasangsthan Bank",
"Bangladesh Red Crescent Society",
"NCC Bank Limited",
"NCC Bank Limited",
"STANDARD BANK LTD",
"Bangladesh Bank High School",
"Brac EPL",
"Premier Bank Limited",
"Premier Bank Limited",
"Al Arafah Islami Bank Limited",
"Al Arafah Islami Bank Limited",
"Dhaka Electric Supply Co",
"SOCIAL ISLAMI BANK LIMITED",
"Woori Bank",
"Bank Al Falah",
"Anti Corruption Commission - ACC",
"Armed Forces Division",
"Ashuganj Power Station Company Ltd (APSCL)",
"Bangladeh Small & Cottage Industries Corporation",
"Bangladesh Academy For Rural Development",
"Bangladesh Administrative Service Association",
"Bangladesh Agricultural Research Council",
"Bangladesh Ansar and Village Defence Party VDP",
"Bangladesh Applied Nutrition and Human",
"Bangladesh Army",
"Bangladesh Bank",
"Bangladesh Bureau of Educational information and Statistics (BANBEIS)",
"Bangladesh Bureau of Statistics",
"Bangladesh Chemical Industries Corporation",
"Bangladesh Civil Service Administration Academy",
"Bangladesh Coast Guard",
"Bangladesh Energy Regulatory Commission",
"Bangladesh Film Development Corporation (BFDC)",
"Bangladesh Forest Department",
"Bangladesh Forest Research Institute",
"Bangladesh Government",
"Bangladesh Government Official Forms",
"Bangladesh Government Press",
"Bangladesh Inland Water Transport Corporation (BIWTC)",
"Bangladesh Institute of Nuclear Agriculture (BINA)",
"Bangladesh Jute Mills Corporation (BJMC)",
"Bangladesh Jute Research Institute",
"Bangladesh Livestock Research institute (BLRI)",
"Bangladesh Madrasha Teachers' Training Institute",
"Bangladesh Marine Academy",
"Bangladesh National Commission for UNESCO (BNCU)",
"Bangladesh National Museum",
"Bangladesh National Scientific and Technical Documentation Centre (BANSDOC)",
"Bangladesh National Social Welfare Coucil",
"Bangladesh Navy",
"Bangladesh Oil, Gas & Mineral Corporation (PETROBANGLA)",
"Bangladesh Ordnance Factories(BOF)",
"Bangladesh Parjatan Corporation",
"Bangladesh Parliament",
"Bangladesh Petroleum Exploration & Production Company Limited (BAPEX)",
"Bangladesh Police",
"Bangladesh Police Reform Programme",
"Bangladesh Post Office",
"Bangladesh Power Development Board",
"Bangladesh Public Service Commission (BPSC)",
"Bangladesh Regional Science Association",
"Bangladesh Rice Research Institute",
"Bangladesh Rifles",
"Bangladesh Road Transport Authority",
"Bangladesh Road Transport Corporation (BRTC)",
"Bangladesh Securities and Exchange Commission (BSEC)",
"Bangladesh Shilpakala Academy",
"Bangladesh Shipping Corporation, Chittagong",
"Bangladesh Small and Cottage Industries Corporation (BSCIC)",
"Bangladesh Social Science Research Council",
"Bangladesh Space Research and Remote Sensing Organization (SpaRRSO)",
"Bangladesh Standards & Testing Institution",
"Bangladesh Tariff Commission (BTC)",
"Bangladesh Tea Board",
"Bangladesh Telecommunication Regulatory Commission",
"Bangladesh Textile Mills Corporation",
"Bangladesh Tourism Board",
"Bangladesh Unnayan Parishad",
"Banglaesh House Building Finance Corporation",
"BANSDOC",
"Barind Multipurpose Development Authority Bangladesh",
"BIWTA Bangladesh Inland Water Transport Authority",
"Board of Intermediate and Secondary Education, Chittagong",
"Board of Intermediate and Secondary Education, Comilla",
"Board of Intermediate and Secondary Education, Rajshahi",
"Board of Investment",
"Border Guard Bangladesh (BGB)",
"Bureau of Manpower, Employment and Training (BMET)",
"Bureau of Non-Formal Education (BNFE)",
"Central Extension Resources Development Institute (CERDI)",
"Central Procurement Technical Unit",
"Chittagong City Corporation",
"Chittagong Development Authority (CDA)",
"Chittagong Hill Tracts Development Board",
"Chittagong Port Authority (CPA)",
"Civil Aviation Authority, Bangladesh",
"Civil Suit Management",
"Controller General Defence Finance (CGDF)",
"Copyright Office, Bangladesh",
"Coastal Security in Bangladesh",
"Cotton Development Board",
"Custom House Chittagong",
"Cyclone Preparedness Programme (CPP)",
"Defence Services Command and Staff College",
"Department of Agricultural Extension",
"Department of Agricultural Marketing",
"Department of Cooperatives Bangladesh",
"Department of Environment",
"Department of Fisheries Bangladesh",
"Department of Immigration & Passports",
"Department of Patents, Designs and Trademarks (DPDT)",
"Department of Shipping (DOS)",
"Department Of Social Services (DSS)",
"Department of Textile",
"Department of Youth Development",
"Deputy Commissioner Bandarban",
"Dhaka Metropolitan Police",
"Dhaka North City Corporation",
"Dhaka Transport Coordination Board (DTCB)",
"Director General of Defenece Purchase (DGDP)",
"Directorate General of Drug Administration (DGDA)",
"Directorate General Of Health Service",
"Directorate of Drugs Administration",
"Directorate of Inspection and Audit (DIA)",
"Directorate Of National Savings (DNS)",
"DIRECTORATE OF NURSING SERVICES",
"Economic Relations Division (ERD), Ministry of Finance",
"Education Board Bangladesh",
"E-Government Procurement (E-GP)",
"Energy And Mineral Resources Division (EMRD)",
"Essential Drugs Company Limited - EDCL",
"Export Promotion Bureau",
"Family Planning Division",
"Ministry of Finance",
"Fisheries Research Institute",
"Hydrocarbon Unit",
"Implementation Monitoring and Evaluation Division (IMED)",
"Institute of Public Health Nutrition (IPHN)",
"Internal Resources Division (IRD)",
"Investment Corporation of Bangladesh",
"Khulna City Corporation",
"Law and Justice Division",
"Legal Registrant of Bangladesh",
"Local Governent Division LGRD",
"Military Institute of Science & Technology (MIST)",
"Ministry of Agriculture",
"Ministry of Civil Aviation & Tourism",
"Ministry of Commerce",
"Ministry of Communication",
"Ministry of Cultural Affairs",
"Ministry of Disaster Management and Relief",
"Ministry of Education",
"Ministry of Environment & Forest",
"Ministry of Expatriates Welfare and Overseas Employment",
"Ministry of Fisheries and Livestock",
"Ministry of Foreign Affairs",
"Ministry of Health and Family Welfare",
"Ministry of Home Affairs",
"Ministry of Industries",
"Ministry of Information",
"Ministry of Information & Communication Technology",
"Ministry of Labour and Employment",
"Ministry of Land",
"Ministry of Law, Justice and Parliamentary Affairs",
"Ministry of Liberation War Affairs",
"Ministry of Planning",
"Ministry of Posts and Telecommunications",
"Ministry of Primary & Mass Education",
"Ministry of Railways ",
"Ministry of Religious Affairs",
"Ministry of Shipping & Inland Water Transport",
"Ministry of Social Welfare",
"Ministry of Textile and Jute",
"Ministry of Water Resources",
"Ministry of Youth and Sports",
"National Academy for Educational Management (NAEM)",
"National Academy for Primary Education (NAPE) Bangladesh",
"National Archives Of Bangladesh",
"National Board of Revenue",
"National Book Center Of BANGLADESH",
"National Curriculum & Textbook Board",
"National Housing Authority (NHA) Bangladesh",
"National Institute of Local Government",
"National Library",
"National Museum of Science & Technology (NMST)",
"National Savings",
"NGO Affairs Bureau (NGOAB)",
"Office of the Comptroller and Auditor General of Bangladesh",
"Palli Daridro Bimochon Foundation (PDBF)",
"Pashchimanchal Gas Company Limited",
"Patuakhali Police",
"Planning Division",
"Posts & Telecommunications Division",
"Power Cell, Ministry of Power, Energy and Mineral Resource",
"Power Division",
"Pragoti Industries Limited",
"Primary and Mass Education",
"Public Finance Foundation",
"Public Works Department",
"Rajdhani Unnayan Kortipakkha (RAJUK)",
"Rangamati Hill district",
"Rangpur Municipal",
"Rapid Action Battalion (RAB)",
"Registrar of Joint Stock Companies and Firms",
"Roads & Highways Department RHD",
"Rupantarita Prakritik Gas Company Limited",
"Rural Development & Cooperative Division",
"Rural Power Company Limited",
"Second Urban Primary Health Care Project",
"Secondary Education Quality and Access Enhancement Project (SEQAEP)",
"Seed Certification Agency",
"SICT Ministry Of Planning",
"Small & Medium Enterprise Foundation",
"Supreme Court of Bangladesh",
"Survey of Bangladesh",
"Sylhet City Corporation",
"The Bangladesh Professional Engineers, Registration Board (BPERB)",
"The Bangladesh Rice Foundation (BRF)",
"The Comprehensive Disaster Management Programme (CDMP)",
"The Directorate of Technical Education (DTE)",
"The National Academy for Educational Management (NAEM)",
"The Security Printing Corporation (Bangladesh) Ltd (SPCBL)",
"Titas Gas Transmission and Distribution Company Limited",
"Trading Corporation of Bangladesh (TCB)",
"Urban Community Volunteer",
"Water Resources Planning Organization (WARPO)",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"APS Group",
"APS Group",
"APS Group",
"APS Group",
"Crown Cements",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"Aliance Holdings & 1Asia Alliance Communication",
"CONCORDE Group",
"CONCORDE Group",
"Danish Dairy Farms Ltd",
"Delsey Cotton Spinning Mills Limited",
"TELE BARTA LIMITED",
"Aman Spinning Mills Ltd",
"Samah Razor Blades Industries Ltd",
"Packman Limited",
"SHOVON GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"DANA GROUP",
"RADIANT AUTOMOATION LTD",
"MONNO CERAMICS",
"Yongtai Industries Bangladesh Ltd",
"PICARD BANGLADESH LIMITED",
"KHADIM CERAMIC WORKS LTD",
"JOHNY TEXTILE MILLS LTD",
"ALLTEX",
"Viquarunnisa Noon School and College",
"PARTEX STAR GROUP",
"ABX LOGISTICS BANGLADESH LTD",
"GSP FINANCE COMPANY (BD) LTD",
"SUN LIFE INSURANCE COMPANY LTD",
"SONALI AANSH INDUSTRIES",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"PARADISE GROUP",
"MINAR INDUSTRIES (PVT) LTD",
"SM GROUP",
"SM GROUP",
"SHINEST GROUP",
"SHINEST GROUP",
"SHINEST GROUP",
"SHINEST GROUP",
"Shepherd Industries Ltd",
"BT Communications Bangladesh Ltd",
"MEL GROUP",
"THE BENGAL PACKAGES",
"Global Capsules Limited",
"Apex Tannery Limited",
"DIPON GROUP",
"NASSA Group",
"Moulana Bhashani Medical College",
"Mahin Group",
"IUBAT",
"Mahin Apparels",
"Convince Apparels",
"Nitol-Niloy Group",
"Nitol-Niloy Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Orion Group",
"Unitrend Limited",
"Habib Group",
"Habib Group",
"Nandan Group",
"European Standard School",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ibn Sina Trust",
"Ornate Group",
"Maple Leaf School",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Mondol Group",
"Ascent Group",
"Ascent Group",
"Ascent Group",
"Ascent Group",
"Ascent Group",
"Aramit Group",
"Fortuna Group",
"Elite Group",
"Radio Today Ltd",
"Delta Hospital",
"East West Medical College",
"Islami Insurance Bangladesh Limited",
"Prime Financial Group",
"Ayurvedic Pharmaceuticals (AP) Ltd",
"Wings Group",
"Dhaka Commerce College",
"Anwar Group",
"Anwar Group",
"Anwar Group",
"Anwar Group",
"Anwar Group",
"Anwar Group",
"A G Automobiles - Concern of Anwar Group",
"MF Consumers Ltd",
"IBAIS University",
"Esquire Knitwear",
"TecAdvantage",
"NR Group ( the Limited Liability Concerns)",
"NR Group ( the Limited Liability Concerns)",
"NR Group ( the Limited Liability Concerns)",
"NR Group ( the Limited Liability Concerns)",
"NR Group ( the Limited Liability Concerns)",
"NR Group ( the Limited Liability Concerns)",
"Gemcon Group",
"The Financial Express",
"Manarat",
"Nuvista Pharma",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Khaled Group",
"Gokaldas Images (Bangladesh) Private Limited",
"Ananda Shipyard & Shipways Ltd",
"Bangla Lion Communication Ltd",
"Integra Group",
"Saudi Bangladesh Industrial and Agricultural Investment Company",
"HRC Ltd",
"DNS Group",
"DNS Group",
"DNS Group",
"Ideal College",
"Midas Financing Limited",
"Milk Vita",
"Central Hospital",
"Kohinoor Chemicals Ltd",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"Tusuka Group",
"National Blind Care Society",
"Agroforestry Improvement Partnership (IC- Leaf project)",
"Keya Group of Industries",
"Holy Family Red Crescent Medical College Hospital",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"S Alam Group of Companies",
"BGMEA (including BUFT)",
"Electra Group",
"Limo Electronics Ltd",
"Bashundhara Group",
"Bangladesh Medical Studies & Research Institute (BMSRI)",
"University of Liberal Arts Bangladesh (ULAB)",
"Fakir Dye and Chemical",
"Federation of Bangladesh Chamber of Commerce and Industries ( FBCCI )",
"Apex Pharma Ltd",
"Apex Investments Ltd",
"Jayson Pharnaceuticals",
"Bracnet",
"Executive Machines Ltd",
"Fashrobe Garments Ltd",
"Asiatic Talking Point",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Purbani Group",
"Daily Prothom Alo",
"Chittagong Chamber of Commerce and Industries",
"Daily Inquilab",
"PSSL-FF",
"Free School Street Property Limited",
"Sikomi Properties Limited",
"Pahartali Power House",
"South East Trading Limited",
"Birshrestho Noor Mohammad Public School & College",
"Danish Food Products",
"Danish Milk Bangladesh Ltd",
"Amber Cotton Mills Ltd",
"Amber Pulp and Paper Mills Ltd",
"Danish Distribution Network Ltd",
"Star Vegetable Oil Mills Limited",
"Star Coconut Mills Limited",
"Dhakacom Ltd (ISP)",
"Fotoroma Ltd",
"University of Dhaka",
"Ferrotechnic Limited",
"Hashem Corporation (Pvt) Ltd",
"Radio Dhaka",
"uPVC Pipes & Fittings",
"Hosaf Group",
"Hosaf Metar Industry Ltd",
"Hosaf International Ltd",
"Hosaf Gene Cure Ltd",
"Hosaf Power Generation Co Ltd",
"Diabetic Association of Bangladesh",
"Euro Knitting and Dyeing Ind Ltd",
"East West University EWU)",
"Shamol Bangla Media Ltd (Banglavision)",
"Jahangir and Others",
"Jahangir and Others",
"Jahangir and Others",
"Jahangir and Others",
"Jahangir and Others",
"Islam Group",
"SAARC Meteorological Research Centre (SMRC)",
"Dhaka City College",
"REHAB",
"BAPEX",
"BKMEA",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Rahmat Group",
"Medical College for Women & Hospital",
"Popular Group",
"Popular Group",
"Popular Group",
"Hamdard Labratories",
"Bangladesh Institute of International and Strategic Studies",
"Bangladesh Erectors Limited",
"Bangladesh Manabadhikar Bastabayan Sangstha:",
"ICMAB-The Institute of Cost and Management Accountants of Bangladesh:",
"Channel 24",
"Ekattor TV",
"Anjuman Mufidul Islam",
"Swanirvar Bangladesh",
"Dhaka Residential Model College",
"Birshrestha Munshi Abdur Rouf Public College",
"Infrastructure Investment Facilitation Centre",
"Rural Electrification Board",
"Comprehensive Holdings",
"Bangladesh Football federation",
"Tele-Talk",
"Institute of Chartered Accountant of Bangladesh (ICAB)",
"SME Foundation",
"Bangladesh Open University",
"West Zone Power Distribution Company Limited",
"Dhaka Dental College and Hospital",
"NEW AGE GROUP",
"KAI Bangladesh Aluminium Limited",
"QC Corporation Ltd",
"Credit Rating Agency of Bangladesh",
"Grameen Danone Foods Ltd",
"Ananda Group",
"Bangladesh Petroleum Institute",
"Sikder Group",
"Sikder Group",
"Sikder Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"Vision Group",
"ELECTION COMMISSION",
"Pendekar Energy (Powertek)",
"BRB Group",
"BRB Group",
"BRB Group",
"BRB Group",
"Shanta Group (STS Group)",
"Eur Service (Bd) Ltd",
"That'S It Sportswear Limited",
"TK Group of Industries",
"Bangla Trac Communication Ltd",
"Shin Shin Group",
"Viyellatex Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Akij Group",
"Armana Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"Well Group",
"HMCL NILOY BANGLADESH LIMITED",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"PRAN RFL Group",
"SINHA GROUP",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"TRANSCOM",
"M M ISPAHANI LTD",
"ENERGYPAC",
"ENERGYPAC",
"ENERGYPAC",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"ACI LTD",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"TK Group of Industries",
"Pacific Jeans Ltd (Pacific Group)",
"KDS Group",
"KDS Group",
"KDS Group",
"KDS Group",
"KDS Group",
"KDS Group",
"ABC Group:",
"Hamid Group",
"Hamid Group",
"Hamid Group",
"Hamid Group",
"Abul Khair Group",
"Abul Khair Group",
"Abul Khair Group",
"Abul Khair Group",
"Abul Khair Group",
"Abul Khair Group",
"Naheed Composite Textile Mills Limited",
"Naheed Cotton Mills Limited",
"JEACON GRAMENTS",
"INTERNATIONAL OFFICE EQUIPMENT (IOE)",
"PRINT PACK INSDUTRIES LTD",
"Blossom Textiles Limited",
"Bombay sweets and Co Ltd",
"Hin Getah Bangladesh Limited",
"GLOBAL BEVERAGE CO LTD",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"ACME GROUP",
"SHAH CEMENT INDUSTRIES LTD",
"APEX GROUP",
"International Leasing & Financial Services Ltd",
"RAHIMAFROOZ",
"RAHIMAFROOZ",
"RAHIMAFROOZ",
"RAHIMAFROOZ",
"Global Heavy Chemicals limited",
"QC CONTAINER LINES",
"Famous Printing and Packaging Ltd",
"K Line Bangladesh Ltd",
"AEG Engineering Ltd",
"Mutual Milk Products/Mutual Food Products Limited",
"Jenny's Footwear Limited",
"REGENSEA LINES LTD",
"SEACOM SHIPPING LTD",
"EVERBEST SHIPPING AGENCIES LTD",
"Hussain Trading Co",
"Mohammadi Group",
"R B Group",
"Viyellatex Group",
"Viyellatex Group",
"Aamra Companies",
"Aamra Companies",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"Shanta Group (STS Group)",
"National Life Insurance",
"Dekko Group",
"Dekko Group",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"Abdul Monem LTD",
"AK KHAN & COLIMITED",
"AK KHAN & COLIMITED",
"AK KHAN & COLIMITED",
"AK KHAN & COLIMITED",
"AK KHAN & COLIMITED",
"Bangla TRAC",
"Bangla TRAC",
"PACIFIC MOTORS LIMITED",
"Unique Group",
"Unique Group",
"Unique Group",
"Unique Group",
"MJL BANGLADESH LTD",
"MJL BANGLADESH LTD",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Noman Group",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"Bengal Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Envoy Group",
"Apex Adelchi Footwear Limited",
"Uttara Group",
"Uttara Group",
"Uttara Group",
"Uttara Group",
"Uttara Group",
"Bangladesh Shipping Corporation",
"BRB Group",
"BRB Group",
"BRB Group",
"BRB Group",
"Kabir Group of Industries (KSRM)",
"Kalpataru Power Transmission Limited",
"USTC",
"Titas Sportswear Industries Ltd",
"Lalmai Sportswear Industries Ltd",
"Karnaphuli Steel Milss Ltd",
"Aftab Group",
"Dhaka Stock Exchange",
"TVS Auto Bangladesh Limited",
"MGH Holdings Ltd",
"Chittagong Jute Manufacturing Co Ltd",
"Nasirabad Properties Limited",
"M M ISPAHANI LTD",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Partex Group",
"Energyprima Ltd",
"CDBL (Central Depository Bangladesh Limited)",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Grameen",
"Bangladesh Petroleum Corporation",
"Bangladesh Petroleum Corporation",
"Bangladesh Petroleum Corporation",
"CityGroup",
"CityGroup",
"CityGroup",
"CityGroup",
"CityGroup",
"ICB",
"ICB",
"Globe Travel Distributions Bangla Pvt Ltd/Amadeus",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"Mir Group of Companies",
"BANGLADESH INTERNATIONAL TUTORIAL",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"BSA Group of Companies",
"STRUCTURED DATA SYSTEMS LIMITED",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"Kumudini Welfare Trust of Bengal (BD)",
"CORR-The Jute Works",
"AMTOB (ASSOCIATION OF MOBILE OPERATORS OF BD) TRUST",
"UNION GROUP",
"UNION GROUP",
"UNION GROUP",
"UNION GROUP",
"UNION GROUP",
"UNION GROUP",
"UNION GROUP",
"Summit Group",
"Summit Group",
"Summit Group",
"Summit Group",
"Summit Group",
"Summit Group",
"GONO SHAKKHARATA OVIJAN/CAMPAIGN FOR POPULAR EDUCATION (CAMPE)",
"HKD International",
"FASHIONIT COMPANY LIMITED",
"Shun Shing Group",
"Shun Shing Group",
"Shun Shing Group",
"Shun Shing Group",
"Shun Shing Group",
"Rahman Rahman Huq (KPMG)",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Confidence Group",
"Paragon Feed Ltd",
"Paragon Poultry Ltd",
"IMPACT FOUNDATION BANGLADESH",
"Orient Energy Systems Ltd",
"UniHealth Manufactureres Ltd-BC",
"PADMA GROUP OF CONVERTERS",
"PADMA GROUP OF CONVERTERS",
"PADMA GROUP OF CONVERTERS",
"PADMA GROUP OF CONVERTERS",
"Al-Karim Paints and Chemicals Ltd",
"Karnaphuli Group",
"Baizid Steels Ltd",
"CIRDAP",
"Genetic Limited",
"Mirpur Ceramics Works",
"UTAH GROUP",
"UTAH GROUP",
"UTAH GROUP",
"Aliance Holdings & 1Asia Alliance Communication",
"Evince Group",
"Evince Group",
"Evince Group",
"Evince Group",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"TMSS",
"Interspeed",
"SOORTY TEXTILE (BD) LIMITED",
"Khaled Group",
"OPEX GROUP/SINHA GROUP",
"OPEX GROUP/SINHA GROUP",
"OPEX GROUP/SINHA GROUP",
"OPEX GROUP/SINHA GROUP",
"OPEX GROUP/SINHA GROUP",
"OPEX GROUP/SINHA GROUP",
"Sinha Medlar Group",
"Edison group",
"Edison group",
"Edison group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"Daffodil Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"US Bangla Group",
"MAX Group",
"MAX Group",
"MAX Group",
"MAX Group",
"MAX Group",
"MAX Group",
"MAX Group",
"Fullcharm Fashion Knitters Ltd",
"Good Times Holding Limited",
"US Bangla Group",
"Aamra Companies",
"Aamra Companies",
"AB Bank Limited",
"ACI Limited",
"ACI LTD",
"ACME GROUP",
"Aman Cotton Fibrous Limited",
"Advent Pharma Limited",
"PRAN RFL Group",
"Apex Holdings Limited",
"Apex Group",
"Apex Holdings Limited",
"Baraka Power Limited",
"BATA",
"BRITISH AMERICANN TOBACOO(BD) LTD",
"Bangladesh Building Systems Ltd (BBS)",
"Bangladesh Finance Limited",
"TRANSCOM",
"BERGER PAINTS BD LTD",
"Bashundhara Group",
"BSRM Group",
"BSRM Group",
"Beximco Group",
"AFC Agro Biotech Limited",
"Aftab Automobiles Limited",
"Alif Industries Limited",
"Aman Feed Limited",
"Ambee Pharmaceuticals Limited",
"Anwar Galvanizing Limited",
"Asian Tiger Sandhani Life Growth Fund",
"Bangas Limited",
"Bangladesh Autocars Limited",
"BDCOM CONNECTING PROGRESS",
"Bangladesh Submarine Cable Company Limited",
"Central Insurance Company Limited",
"The City Bank",
"Confidence Group",
"Coppertech Industries Limited",
"DELTA BRAC HOUSING CORPORATION LTD",
"Delta Life Insurance",
"Dhaka Insurance Ltd",
"Islam Group",
"Evince Group",
"DOREEN GROUP",
"Desh Garments Limited",
"Dragon Sweater & Spinning Limited",
"Eastern Insurance Company Limited",
"Eastland Insurance Company Limited",
"Eastern Lubricants Limited",
"Esquire Knit Composite Limited",
"Far East Knitting and Dyeing Industries Limited",
"GBB Power Limited",
"Golden Harvest Group",
"UNILEVER CONSUMER CARE LIMITED",
"GRAMEEN PHONE LTD",
"GPH ISPAT LTD",
"GREEN DELTA INSURANCE",
"HEIDELBERG CEMENT/SCAN CEMENT BD LTD",
"PRIDE GROUP",
"IDLC",
"IFIC Bank",
"ISLAMI BANK BANGLADESH LIMITED",
"IT CONSULTANTS LIMITED",
"Janata Insurance Ltd",
"JMI Syringes & Medical Devices Limited",
"KDS Group",
"Khulna Power Distribution Company",
"Lanka Bangla",
"LAFARGE HOLCIM BANGLADESH LTD",
"Libra Infusions Limited",
"Linde Bangladesh limited ( former BOC Bangladesh Limited )",
"L R Global",
"Malek Spinning Mills Ltd",
"MARICO BANGLADESH LIMITED",
"DBL Group",
"MEGHNA CEMENT",
"Mercantile Bank",
"M I Cement",
"Mobil Jamuna lubricant Ltd",
"NAVANA LIMITED",
"New Line Clothings Ltd",
"Olympic Industries",
"Orion Group",
"Phoenix Group ( Phoenix Finance , Phoenix Securities, Phoenix Insurance )",
"PRAGATI INSURANCE LIMITED",
"Premier Cement",
"Prime Insurance",
"Progressive Life Insurance Company Ltd",
"Paramount Textile Limited",
"Quasem Group (Quasem Industries Limited, Quasem Lamps Ltd, Quasem Foods Ltd, Quasem Foundation)",
"Queen South Textiles Ltd",
"Rahim Textiles Mills",
"RAK Group",
"PRAN RFL Group",
"RECKITT BENCKISER",
"TRANSCOM",
"RENATA LTD",
"Republic Insurance Company",
"Ring Shine Textiles Ltd",
"Ratanpur Steel Re-Rolling Mils Ltd (RSRM)",
"Runner Group",
"SAIF Powertec Limited",
"MH Samorita Medical College & Hospital",
"Summit Group",
"Shasha Denims Ltd",
"Shurwid Industries",
"SINGER BANGLADESH LTD",
"Sino Bangla Industries Ltd",
"SQUARE GROUP",
"SQUARE GROUP",
"Standard Insurance Limited",
"Stylecraft Limited",
"Trust Bank Limited",
"United Finance Limited",
"United Group",
"UTTARA BANK LIMITED",
"Western Marine Group",
"Active Fine Chemical Ltd",
"Active Fine Chemical Ltd",
"AGNI SYSTEMS LIMITED",
"Agrani Insurance Ltd",
"Aziz Pipes Limited",
"Central Pharmaceuticals Ltd",
"FU-WANG CERAMIC INDUSTRY LIMITED",
"Fu-Wang Foods Ltd",
"Information Service Network (ISN)",
"Makson Group",
"Mercantile Insurance Company",
"Makson Group",
"Miracle Industries Ltd",
"Prime Textile Spinning Mills Ltd",
"Zahintex Ltd",
"Far Chemical Industries Limited",
"First Bangladesh Fixed Income Fund",
"Fortune Shoes Limited",
"Gemini Sea Food Limited",
"Genex Infosys Limited",
"GQ Ball Pen Industries Limited",
"Grameen One : Scheme Two",
"HWA Well Textiles (BD) Limited",
"Intraco Refueling Station Limited",
"IPDC Finance Limited",
"Islamic Insurance Bangladesh Limited",
"Jamuna Oil Company Limited",
"Karnaphuli Insurance Company Limited",
"Kattali Textile Limited",
"M L Dyeing Limited",
"Monno Jute Staffers Limited",
"Nahee Group",
"Nahee Group",
"Nahee Group",
"Nitol Insurance Company Limited",
"Northern Jute Manufacturing Company Limited",
"Northern Islami Insurance Limited",
"National Tea Company Limited",
"National Tubes Limited",
"Nurani Dyeing & Sweater Limited",
"Oimex Electrode Limited",
"Pacific Denims Limited",
"Pharma Aids",
"Pragati Life Insurance Company Limited",
"Purabi Gen Insurance Company Limited",
"Renwick Jajneswar & Company (BD) Limited",
"Saiham Cotton Mills Limited",
"Saiham Textile Mills Limited",
"Sandhani Life Insurance Company Limited",
"Silco Pharmaceuticals Limited",
"Simtex Industries Limited",
"SK Trims & Industries Limited",
"Sonar Bangla Insurance Limited",
"Shahjibazar Power Company Limited",
"S S Steel Limited",
"Takaful Islami Insurance Limited",
"Vanguard AML BD Finance",
"VF Thread Dyeing Limited",
"Wata Chemicals Limited",
"Anlimayam Dyeing Limited",
"Atlas Bangladesh Limited",
"City General Insurance Company Limited",
"CVO Petrochemical Refinery Limited",
"Deshbandhu Polymer",
"Eastern Cables Limited",
"Fine Foods Limited",
"Hakkani Pulp & Paper Mills Limited",
"Kay & Que Bangladesh Limited",
"Khan Brothers PP Woven Bag Industries Limited",
"Legacy Footwear Limited",
"Mozaffar Hossain Spinning Mills Limited",
"Olympic Accessories Limited",
"Paramount Insurance Company Limited",
"Peoples Insurance Company Limited",
"Rangpur Dairy & Food Products",
"Safko Spinning Mills Limited",
"Salvo Chemical Industry Limited",
"Samata Leather Complex Limited",
"Sonargaon Textiles Limited",
"Shinepukur Ceramics Limited",
"Tosrifa Industries Limited",
"Yeakin Polymer Limited",
"Zaheen Spinning Limited",
"Bangladesh Krishi Bank",
"Prime Asset Group",
"China Petroleum Pipeline Engineering Company Limited",
"Edison group",
"Therap BD",
"Nitol-Niloy Group",
"Ahsania Mission",
"Amanat Shah Group",
"Community Bank Bangladesh Limited",
"Modhumoti Bank Limited",
"PHARMA SOLUTIONS BANGLADESH LIMITED ",
"TECH VALLEY COMPUTERS LTD",
"PHP Group",
"PHP Group",
"PHP Group",
"PHP Group",
"PHP Group",
"National Polymer Industries Ltd",
"MGH GROUP",
"Edcon International (Singapore) PTE LTD",
"SITA Information Networking Computing BV",
"Thakral Information Systems Private Ltd",
"Co water International",
"NATIONAL DEMOCRATIC INSTT (NDI)",
"HAREWELLE INTERNATIONAL LIMITED",
"CNFA",
"ADD International - Action on Disability and Development",
"IFDC",
"QUALITY PAPER MILL LTD",
"PDS Multinational / Deepak Seth Group",
"Simba Fashions Limited",
"Continental Insurance Company Limited",
"UTAH GROUP",
"ASIA INSURANCE LIMITED",
"Hamid Fabrics Ltd",
"METRONET BANGLADESH LTD",
"Beacon Pharmaceuticals",
"DBL Group",
"RRM Group",
"Asian Disaster Preparedness Centre",
"UTAH GROUP",
"Evince Group",
"Butterfly Marketting Limited",
"Flora Ltd",
"Standard Asiatic Oil Company",
"Asia Energy Corporation (Bangladesh) PTY Ltd",
"NDB Capital",
"Hamid Group (Garments)",
"Hamid Group (Garments)",
"Arannayk Foundation",
"Dada Group",
"Dada Group",
"GOODMAN COMPANY LIMITED",
"Independent TV",
"JOHN SNOW INC (JSI)",
"SOUTH ASIA PARTNERSHIP BANGLADESH",
"SWISS COLOURS BANGLADESH LIMITED",
"Embassy of Maldives -HIGH COMMISSION OF THE REPUBLIC OF MALDIVES",
"UNITED DEVELOPMENT INITIATIVES FOR PROGRAMMED ACTIONS",
"INTERNATIONAL JUTE STUDY GROUP",
"ORASINVEST (BANGLADESH) LTD",
"Haddad Organization",
"China National Electrical Wire Company",
"IBM Bangladesh",
"Concern Universal",
"Isolux Corsan/Isolux Ingenieria SA",
"Project Concern International",
"Ajinomoto Bangladesh",
"PROGRAM SUPPORT UNIT/CIDA",
"Alifia Properties Ltd-CIC",
"ARD, INC",
"CEMEX CEMENT BANGLADESH LTD",
"PEL BANGLADESH SERVICES LIMITED",
"Eastern Atlas Ltd",
"AUTOMATION ENGINEERING AND CONTROLS LTD",
"MEDICO Sports Fashion GmbH",
"Ahead Logistics",
"Always on Network Bangladesh",
"Gram Unnyan Karma",
"Indesore Group",
"Indesore Group",
"Indesore Group",
"Indesore Group",
"Indesore Group",
"Centre for Development Services",
"Origin Logistics",
"Kemiko Pharmaceuticals Limited",
"Pharaoh Communications Ltd",
"Nagar Homes",
"Kaltimex Energy Bangladesh (Pvt) Ltd",
"Intramex Group",
"Eon Animal Health Products Limited -EB",
"A-One BD Limited",
"Junior Laboratory (PVT) Ltd",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"Golden Harvest Group",
"THE DATABIZ SOFTWARE LTD",
"Advanced ERP (BD) Ltd",
"Bangladesh Institute of Labour Studies",
"Bestec Group",
"Interspeed -BC",
"HB CONSALTANTS LTD",
"Signage Group",
"ASSURANCE MONI GROUP",
"Islam Group",
"Islam Group",
"Handicap International",
"Danchurch Aid (DCA)",
"CodeMate",
"Mothercare Sourcing Division Bangladesh",
"MNC Apparels Ltd",
"Dynasty Group Ltd",
"RRM Group",
"RRM Group",
"RRM Group",
"TK Group of Industries",
"Hamid Group (Garments)",
"Shanta Group (STS Group)",
"Grabal Alok (UK) Limited",
"NOKON Ltd",
"Panache Knitted Creations Ltd",
"Toy Woods (BD) Co Ltd",
"CONVEYOR LOGISTICS LTD",
"METRO MAKERS AND DEVELOPERS LTD",
"Building Technology and Ideas-BC",
"Foreign Investors Chamber of Commerce and Industries -BC",
"Evince Group",
"Brainchild Communication Bangladesh Limited",
"BURO BANGLADESH",
"Spectrum Lanka Technology Solutions Ltd",
"SMCC-ITD JV",
"W3 ENGINEERS LTD",
"University of Asia Pacific Banglades (UAP)",
"BRAC University (BRAC)",
"ASA University Bangladesh (ASAUB)",
"Atish Dipankar University of Science and Technology (ADUST)",
"Shanto-Mariam University of Creative Technology (SMUCT)",
"Eastern University Bangladesh (EUB)",
"State University Of Bangladesh (SUB)",
"Stamford University Bangladesh (SU)",
"International University of Business Agriculture & Technology (IUBAT)",
"American International University Bangladesh (AIUB)",
"Ahsanullah University of Technology (AUST)",
"United International University (UIU)",
"Bangladesh University of Business & Technology (BUBT)",
"University of Development Alternative (UODA)",
"Southeast University (SEU)",
"DOREEN GROUP",
"Groz-Beckert",
"E Courier Limited",
"Partex Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"Noman Group / Saad Group",
"BAF Shaheen English Medium School",
"BIMS",
"Hurdco International School",
"International Hope School Bangladesh",
"Manarat Dhaka International School and College",
"Oxford International School",
"Playpen School",
"SCHOLARS INTERNATIONAL SCHOOL",
"Singapore International School",
"Sir John Wilson School",
"SOUTH BREEZE SCHOOL",
"Sunbeams School",
"Sunnydale School",
"Sunshine Grammer School",
"Australian International School",
"International School Dhaka",
"Cardiff International School Dhaka (CISD)",
"Daffodil International School",
"European Grammar School",
"Yale International School",
"SALVATION INTERNATIONAL SCHOOL AND COLLEGE",
"Bengal Group",
"Partex Group",
"ASA",
"Ridoy Rifat Industries Ltd",
"Swiss Bio hygienic Equipment Ltd",
"Dhaka Shishu Hospital",
"FIELD INFORMATION SOLUTIONS LTD",
"TEEN AGE MODERN FASHION LTD",
"DHAKA INTERNATIONAL UNIVERSITY",
"HOLY SYLHET HOLDINGS LTD",
"ADC",
"Crown Exclusive Wears Ltd.",
"KAZI AGRO LTD",
"UTTARA CRESENT CLINIC LTD",
"RAINBOW LOGISTICS LTD",
"HAQUE",
"SALAM STEEL CONCAST RE-ROLLING MILLS LTD",
"MODE MAKERS",
"Designer Fashion Ltd",
"DEKKO LEGACY GROUP (RMG)",
"DARAZ BANGLADESH LTD",
"ORIENT ALLURE KNITWEAR LTD",
"BENGAL BEE LTD",
"MADINA POLY FIBRE LTD",
"NET 71",
"RADIANT AVIATION",
"NATIONAL CREDIT RATINGS LTD",
"BEST SHIRTS LTD",
"ARCOBALENO FOOTWEAR LTD",
"BRIGHT RIVER BANGLADESH LTD",
"ASIATIC SOCIETY OF BANGLADESH",
"GREENLAND PHARMACEUTICALS LTD",
"CRAFTSMEN LTD",
"ZASS Telecom LTD",
"NORBAN COMTEX LIMITED",
"JOYCALLS BANGLADESH LTD",
"AJI GROUP",
"TUNIC APPARELS LTD",
"VERSATILE CEATION LTD",
"A K KHAN & COMPANY LTD",
"COAL POWER GENERATION COMPANY BANGLADESH",
"MGH Group",
"Robert Bosch (Bangladesh) Ltd ",
"Nippon Paint (Bangladesh) Private Ltd ",
"KYCR COIL INDUSTRIES LIMITED",
"United Group",
"Dhaka South City Corporation",
"Disabled Rehabilitation and Research Association (DRRA)",
"X SOLUTIONS LTD",
"CONCRETE & STEEL TECHNOLOGIES LTD",
"ABANTI COLOR TEX LTD",
"AMBER DENIM MILLS LTD",
"HELLENIC SOURCING HONG KONG LTD",
"MY SOFT LTD",
"SYLHET WOMEN'S MEDICAL COLLEGE HOSPITAL",
"METROCEM",
"ADN TECHNOLOGY",
"WEBLINK COMMUNICATION LTD",
"FILAMENT ENGINEERING LTD",
"AVENUE TRADE & ENGINEERING",
"SURJER HASHI NETWORK",
"LUB RREF BD LTD",
"A K KHAN & COMPANY LTD",
"YANGMING HANHAI (BANGLADESH) LTD",
"SIGNIFY BANGLADESH LTD",
"JUST JAMES BD LTD",
"CG APPAREL LTD",
"ALIF EMBROIDERY VILLAGE LTD",
"GANA UNNAYAN KENDRA",
"QUICKLY GLOBAL LTD",
"DESIGN ACE LTD",
"EON FOOD LTD",
"TIFFIN BOX LIMITED",
"DENIM FASHION LTD",
"AMAN CEMENT MILLS UNIT-2 LTD",
"AMAN GROUP",
"DYSIN GROUP",
"CONCITO PR (PVT) LTD",
"GARAN MANUFACTURING CORPORATION",
"NIPPON PAINT (BANGLADESH) PRIVATE LTD",
"EURO PHARMA LTD",
"RISHAL GARMENTS LTD",
"IDS Group",
"Kona Software Lab Limited",
"NORTH WEST POWER GENERATION COMPANY LTD",
"AMAN GROUP",
"Global Alliance for Improved Nutrition ",
"AGRANI BANK ",
"JANATA BANK LIMITED",
"JAMUNA GROUP",
"Dhaka Cantonment Girls' Public School and College",
"PARTEX STAR GROUP",
"Savoy Ice Cream Factory Ltd",
"ACI GROUP",
"MULTIFABS LIMITED",
"Bengal Commercial Bank",
"SHIMANTO BANK LIMITED",
"Akij Group",
"HAMEEM GROUP",
"New Star Hilon Co Ltd",
"ANANTA APPARELS LIMITED",
"ADCOMM LTD",
"SQ Group",
"Veritas Pharmaceuticals Limited",
"Research, Training and Management International",
"Partex / Amber Group ",
"NATIONAL BANK LIMITED",
"Bengal Communication Limited",
"JAMUNA GROUP",
"Crystal Group CRYSTAL CARS",
"Adobe Builders Ltd",
"DYSIN GROUP",
"DYSIN GROUP",
"Meghna Bank",
"BIAM MODEL SCHOOL & COLLEGE",
"Institute of Water Modelling",
"SARA LIFESTYLE LTD",
"First Security Islami Bank Limited (FSIBL)",
"NRB COMMERCIAL BANK LIMITED",
"Bangladesh International School and College",
"Bproperty",
"Silver Line Composite Textile",
"DYSIN GROUP",
"Pretty Group",
"GUARDIAN LIFE INSURANCE LIMITED",
"Louietex",
"Aparajeyo Bangladesh",
"Asia Energy Corporation (Bangladesh) PTY Ltd",
"Abul Khair Group",
"Epic Group",
"Embassy of Indonesia",
"Youngone Corporation",
"UCEP - Bangladesh",
"Agricultural Extension Component (AEC)",
"PHP Group",
"PHP Group",
"ZTE CORPORATION (BD OFFICE)",
"Unimed & UniHealth Manufacturers Ltd",
"Sir William Beveridge Foundation",
"Echotex",
"Fiber @ Home",
"Shakti Foundation",
"Mennonite Central Committee (MCC)",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Runner Group",
"Muslim Aid - UK",
"Active Fine Chemical Ltd",
"Patenga Footwear (Pvt) Limited",
"Matador",
"Matador",
"Matador",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"PARTEX STAR GROUP",
"FU WANG GROUP",
"SHINEST GROUP",
"Nourish Agro Ltd",
"Nitol-Niloy Group",
"Nitol-Niloy Group",
"Signage Group",
"Sheltech (PVT) Ltd",
"Habib Group",
"SQ Group",
"Impress Group (Channel I)",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Palmal Group",
"Mondol Group",
"Mondol Group",
"Ascent Group",
"Elite Group",
"Elite Group",
"Elite Group",
"Dhaka Commerce College",
"DIPON GROUP",
"Anwar Group",
"Manarat",
"NTV",
"Willes Little Flower School",
"Building For Future",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"Lab Aid Group",
"ASSURANCE MONI GROUP",
"ASSURANCE MONI GROUP",
"Oriental Real Estate",
"Fakir Knitwear",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"Bashundhara Group",
"The Daily Samakal",
"Bashundhara Group",
"Bangladesh Medical Studies & Research Institute (BMSRI)",
"Islami Bank Foundation",
"FAKIR FASHION",
"Rupayan Group",
"Islamic Bank Foundation Group",
"Meghna Group",
"Meghna Group",
"Meghna Group",
"Meghna Group",
"Meghna Group",
"Broad Band Telecom Services Limited",
"EXIM Bank Hospital",
"Star Particle Board Mills Ltd",
"Chittagong Grammer School",
"Jalalabad Ragib Rabea Medical College and Hospital",
"Bangladesh Sangbad Santha",
"Islam Group",
"Islamic Foundation",
"Makson Group",
"Makson Group",
"Makson Group",
"Makson Group",
"Makson Group",
"Makson Group",
"Crony Group",
"Crony Group",
"Crony Group",
"Crony Group",
"Crony Group",
"Crony Group",
"Premier Leasing and Finance Limited",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Fashion Product Group",
"Midland Bank",
"Farmer's Bank",
"Grameen Knitwear",
"International Islamic University Chittagong",
"Ranks ITT",
"Kuwait Embassy",
"GERAMAN TECHNICAL COOPERATION",
"COVANTA BANGLADESH OPERATING LTD",
"Clariant (Bangladesh) Ltd",
"Halcrow Bangladesh Limited",
"Smiling Sun Franchise Program",
"GEC",
"Niko Resources (Bangladesh) Limited",
"ThyssenKrupp Elevator (BD) Pvt Ltd",
"Eltek Valere",
"GTL",
"Youn An Hat Bangladesh",
"CMA CGM Bangladesh Shipping Ltd",
"TNT Express",
"Young An Hat",
"Dascher",
"TKM Global",
"Areva T & D",
"Marks & Spencer",
"Dun & Bradstreet Rating Agency Bangladesh/Dun and Bradstreet",
"Target Sourcing Services/AMS",
"Newtimes Group",
"ITC Logistics",
"Agreeya Solutiions",
"GroupeCarrefour",
"DAI",
"Dachser",
"HelpAge International (HAI) Bangladesh",
"Education and Development Foundation-Educo",
"Alcatel Lucent",
"Thomson Reuters",
"Crystal Martin Holdings Ltd",
"Union de Banques Arabes et Francaises (UBAF)",
"Fael Khaer Program (IDB)",
"The Islamic Corporation for the Insurance of Investment and Export Credit (IDB)",
"Mott MacDonald (Group as a whole and the concerns)",
"Saudi Bangladesh Investment Company",
"Medicins Sans Frontier / Dotors without Border",
"ESCENIC ASIA",
"Sun Fortune Limited",
"USC CANADA BANGLADESH",
"Regent Global Sourcing",
"Augere Bangladesh Ltd",
"Aramex",
"Daewoo International Corporation",
"Western Union Money Exchange",
"Hanjing Shipping",
"Silvia ShipTrade",
"Hewlett Packard",
"Polyconcept Group",
"Polyconcept Group",
"Mission Aviation Fellowship (MAF) -Sweden",
"ICICI Bank Representative Office",
"ITS: International Turnkey Systems",
"Starship Maritime",
"Partners in Health and Development",
"Pulcra Chemicals Limited",
"Rohto-Mentholatum (Bangladesh) Limited:  ",
"Ogilvy Mather",
"Checkpoint Systems Bangladesh Limited",
"International Network of Alternative Financial Institutions",
"ACCA",
"BSI Inspectorate",
"Action for Enterprises Limited",
"The Children's Place",
"Pendekar Energy (Powertek)",
"Good Neighbour",
"Mashreq Bank",
"Benetton Asia Pacific Ltd",
"LG Electronics Singapore Pte Limited:",
"Orbis International",
"Canadian International Developement",
"German Technical Cooperation",
"QUBEE",
"Microsoft Bangladesh Limited",
"Elanco Bangladesh Limited",
"GENESIS DENIM LIMITED",
"Shin Shin Group",
"Viyellatex Group",
"Viyellatex Group",
"DBL Group",
"DBL Group",
"DBL Group",
"DBL Group",
"DBL Group",
"Hkd Outdoor Innovations Limited",
"Summit Group",
"Lava International (Bangladesh) limited",
"Axis Bank",
"Well Group",
"Chittagong Power Company Limited",
"International Air Transport Association (IATA)",
"PRAN RFL Group",
"PRAN RFL Group",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"NAVANA LIMITED",
"TRANSCOM",
"TRANSCOM",
"IUB (Independent University Bangladesh)",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"SQUARE GROUP",
"ACI LTD",
"AK Khan & Co Ltd",
"KDS Group",
"KDS Group",
"KDS Group",
"Armana Group",
"Armana Group",
"Armana Group",
"Armana Group",
"Armana Group",
"Armana Group",
"Beximco Group",
"Beximco Group",
"ACME GROUP",
"ASA INTERNATIONAL",
"SUPER REFINERY (PVT) LIMITED",
"R B Group",
"R B Group",
"Shanta Group (STS Group)",
"Abdul Monem LTD",
"Bangla TRAC",
"Bangla TRAC",
"Unique Group",
"MJL BANGLADESH LTD",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"Asiatic Marketing Ltd",
"United Group",
"United Group",
"United Group",
"United Group",
"United Group",
"Envoy Group",
"Envoy Group",
"BRB Group",
"Kabir Group of Industries (KSRM)",
"USTC",
"MGH Group",
"Grameen",
"Brac Bank Limited",
"AB Bank Limited",
"BSA Group of Companies",
"EXCEL TELE-COM (PVT) LTD",
"Confidence Group",
"Confidence Group",
"IMPACT FOUNDATION BANGLADESH",
"SIEMENS BD LIMITED",
"MOTOROLA TELECOMMUNICATIONS BANGLADESH PVT LTD",
"SEARS Holding Global Sourcing",
"UPS SCS BD LTD",
"Finlay Limited",
"Crystal Group CRYSTAL CARS",
"Crystal Group CRYSTAL CARS",
"Crystal Group CRYSTAL CARS",
"National Bank of Pakistan",
"Ring Shine Textiles Ltd",
"United Bank of India",
"Embassy of Brazil",
"Embassy of Russia",
"DNV GL BANGLADESH LIMITED (Previously known as GERMANISCHER LLOYD BANGLADESH LTD)",
"Vertive (Bangladesh) PVT LTD",
"SWISS DEVELOPMENT COOPERATION",
"The Micronutrient Initiative / Nutrition International",
"Wells Fargo Bank N A representative office",
"Royal Embassy of Saudi Arabia",
"Weatherford",
"Caritas Bangladesh",
"Habib Bank AG Zurich Representative Office",
"Production Services Network",
"Schlumberger Limited",
"Kerry Logistics",
"Lepra Bangladesh",
"Bharat Heavy Electricals Ltd (BHEL)",
"Swiss Red Cross",
"General Electric International",
"KEC International Limited",
"Geokinetics Ltd",
"LI & FUNG (BANGLADESH) LIMITED",
"Building Technology and Ideas-BC",
"Baizid Steels Ltd",
"Intercontinental Hotel",
"Matador",
"Meghna Group of Industries (MGI)",
"Meghna Group of Industries (MGI)",
"Interspeed",
"Nour Bangla/ Munir Sulhtian International Ltd",
"Stromme Foundation",
"British Broadcasting Corporation (BBC)",
"British Broadcasting Corporation (BBC)",
"BJ Services Company Middle East Ltd",
"British Broadcasting Corporation (BBC)",
"Edison group",
"US Bangla Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"Four H Group",
"CLASSNK (Nippon Kaiji Kyokai)",
"Expo Group",
"Expo Group",
"Expo Group",
"Expo Group",
"Expo Group",
"Incepta Herbal & Nutricare Ltd",
"Premier University",
"Bangladesh Pou Hung Industrial Ltd",
"The Himalaya Drug Company Ltd",
"The Doha Bank",
"JAMUNA SPACETECH JOINT VENTURE LIMITED",
"Gulf Oil Bangladesh Limited",
"AS Bangladesh",
"Enfants Du Monde",
"Solar Electro Bangladesh Ltd",
"OBAYASHI Corporation",
"Alcon Pharmaceuticals Limited",
"Eptisa",
"Chrom World",
"IC Net Limited",
"Quest Holdings Bangladesh Pvt Ltd",
"CBM (Christian Blind Mission)",
"Nagad (Third Wave Technologies Limited)",
"Fuwang Polymer Industry Limited",
"JSC Institute ORGENERGOSTROY",
"JHPIEGO",
"KR Group",
"SMART TECHNOLOGIES BD LTD",
"SNOWTEX SPORTSWEAR LTD",
"Catholic Relief Services",
"ENERGYPAC",
"F5 Networks Bangladesh Ltd",
"French Development Agency (FDA)",
"Ecorys UK Limited",
"Think Well",
"Fonterra",
"E-VALYCOM LIMITED",
"Sharif Group",
"Intelligent Label Solutions",
"Taskeater Bangladesh Limited",
"UCBL Group",
"Directorate of Secondary & Higher Education (Govt Org)",
"Banga Plastic International Ltd",
"ACME Group",
"Syngenta Bangladesh",
"Danish Refugee Council",
"Bangladesh Navy",
"Bangladesh Rifles",
"Bangladesh Tea Board",
"National Board of Revenue",
"Posts & Telecommunications Division",
"Power Cell, Ministry of Power, Energy and Mineral Resource",
"Public Works Department",
"First Janata Bank",
"Nahee Group",
"Nahee Group",
"URMI Group",
"URMI Group",
"Manarat International University (MIU)",
"Partex Group",
"BJIT Limited",
"Dhaka Shishu Hospital",
"Robert Bosch (Bangladesh) Ltd ",
"KYCR COIL INDUSTRIES LIMITED",
"Disabled Rehabilitation and Research Association (DRRA)",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"SMART TECHNOLOGIES BD LTD",
"Kona Software Lab Limited",
"Global Alliance for Improved Nutrition ",
"AGRANI BANK ",
"FORTIS GROUP",
"FORTIS GROUP",
"FORTIS GROUP",
"SPECIAL SECURITY FORCE "]

let companyName = ['DANA GROUP',
'RADIANT PHARMACEUTICALS LIMITED',
'NORTH SOUTH UNIVERSITY (NSU)',
'Esquire Group',
'Esquire Electronics',
'Orion Group',
'Ascent Group',
'Popular Pharmaceuticals',
'BIRDEM',
'Keya Cosmetics Ltd',
'Dhaka National Medical College',
'Gulshan Club Limited',
'National Heart Foundation',
'S Alam Group of Companies',
'Bangladesh Medical Studies & Research Institute (BMSRI)',
'Islami Bank Institute of Technology',
'Brac University',
'IIDFC',
'Bangladesh Water Development Board',
'IFIC Bank',
'Kallol Group',
'Dhaka Club',
'Dhaka Chamber of Commerce & Industry',
'Siddheswari Girls College',
'Bangabandhu Sheikh Mujib Medical University',
'Bangladesh Institute of Bank Management',
'DOREEN GROUP',
'Islamic Relief',
'Tetrapak (BD) Ltd',
'Phillip Morris',
'PDS Multinational Group',
'Islamic University of Technology (IUT), Banlgadesh',
'The Alliance Française',
'High Commission of India',
'BSRM Group',
'Sajida Foundation',
'TRANSCOM',
'ACI LTD',
'Flora Ltd',
'Mohammadi Group',
'Kazi Farms',
'Shanta Group (STS Group)',
'Abdul Monem LTD',
'Nasir Group',
'Bangla TRAC',
'Aristopharma',
'Bengal Group',
'Power Grid Company of Bangladesh',
'Kabir Group of Industries (KSRM)',
'Youngone Corporation',
'Palli Karma Sahayak Foundation',
'Partex Group',
'Dhaka Power Distribution Company Ltd',
'Grameen',
'Eastern Bank Limited',
'PUBALI BANK LTD',
'UCBL',
'Mutual Trust Bank Limited',
'DHAKA BANK',
'NATIONAL BANK LIMITED',
'SOUTHEAST BANK LTD',
'Exim Bank Limited',
'One Bank Limited',
'Bangladesh Petroleum Corporation',
'JAMUNA BANK LIMITED',
'BANGLADESH COMMERCE BANK',
'Mir Group of Companies',
'Homebound Packers and Shippers Ltd',
'ISLAMI BANK BANGLADESH LIMITED',
'SHAHJALAL ISLAMI BANK LIMITED',
'PACIFIC ZIPPER BANGLADESH LTD',
'RAK Group',
'Commercial Bank of Ceylon',
'HSBC',
'Citibank NA',
'Mitsubishi Corporation',
'German Red Cross',
'ABF Investments PLC',
'CapitaLand Development Ltd',
'Ispahani Islamia Eye Institute and Hospital',
'Edison group',
'Daffodil Group',
'Rupali Bank',
'Bangladesh-Malaysia Chamber of Commerce and Industry (BMCCI)',
'Total Transportation Ltd – CSCL',
'Bangladesh Foreign Trade Institute',
'National Housing Finance and Investment Limited',
'Islamic Finance and Investment Ltd',
'Shaheed Ramizuddin Cantonment College',
'National Finance Limited',
'Bangladesh University',
'Dhaka Cantt Girl\'s Public School and College',
'BEPZA',
'DUTCH BANGLA BANK LIMITED (DBBL)',
'South Bangla Agriculture & Commerce Bank Ltd',
'Islamic Development Bank –BISEW',
'NRB Bank',
'Union Bank',
'NRB Commercial Bank Limited',
'GLOBAL ISLAMI BANK',
'Karmasangsthan Bank',
'Bangladesh Red Crescent Society',
'NCC Bank Limited',
'STANDARD BANK LTD',
'Bangladesh Bank High School',
'Brac EPL',
'Premier Bank Limited',
'Al Arafah Islami Bank Limited',
'Dhaka Electric Supply Co',
'SOCIAL ISLAMI BANK LIMITED',
'Woori Bank',
'Bank Al Falah',
'Anti Corruption Commission - ACC',
'Armed Forces Division',
'Ashuganj Power Station Company Ltd (APSCL)',
'Bangladeh Small & Cottage Industries Corporation',
'Bangladesh Academy For Rural Development',
'Bangladesh Administrative Service Association',
'Bangladesh Agricultural Research Council',
'Bangladesh Ansar and Village Defence Party VDP',
'Bangladesh Applied Nutrition and Human',
'Bangladesh Army',
'Bangladesh Bank',
'Bangladesh Bureau of Educational information and Statistics (BANBEIS)',
'Bangladesh Bureau of Statistics',
'Bangladesh Chemical Industries Corporation',
'Bangladesh Civil Service Administration Academy',
'Bangladesh Coast Guard',
'Bangladesh Energy Regulatory Commission',
'Bangladesh Film Development Corporation (BFDC)',
'Bangladesh Forest Department',
'Bangladesh Forest Research Institute',
'Bangladesh Government',
'Bangladesh Government Official Forms',
'Bangladesh Government Press',
'Bangladesh Inland Water Transport Corporation (BIWTC)',
'Bangladesh Institute of Nuclear Agriculture (BINA)',
'Bangladesh Jute Mills Corporation (BJMC)',
'Bangladesh Jute Research Institute',
'Bangladesh Livestock Research institute (BLRI)',
'Bangladesh Madrasha Teachers\' Training Institute',
'Bangladesh Marine Academy',
'Bangladesh National Commission for UNESCO (BNCU)',
'Bangladesh National Museum',
'Bangladesh National Scientific and Technical Documentation Centre (BANSDOC)',
'Bangladesh National Social Welfare Coucil',
'Bangladesh Navy',
'Bangladesh Oil, Gas & Mineral Corporation (PETROBANGLA)',
'Bangladesh Ordnance Factories(BOF)',
'Bangladesh Parjatan Corporation',
'Bangladesh Parliament',
'Bangladesh Petroleum Exploration & Production Company Limited (BAPEX)',
'Bangladesh Police',
'Bangladesh Police Reform Programme',
'Bangladesh Post Office',
'Bangladesh Power Development Board',
'Bangladesh Public Service Commission (BPSC)',
'Bangladesh Regional Science Association',
'Bangladesh Rice Research Institute',
'Bangladesh Rifles',
'Bangladesh Road Transport Authority',
'Bangladesh Road Transport Corporation (BRTC)',
'Bangladesh Securities and Exchange Commission (BSEC)',
'Bangladesh Shilpakala Academy',
'Bangladesh Shipping Corporation, Chittagong',
'Bangladesh Small and Cottage Industries Corporation (BSCIC)',
'Bangladesh Social Science Research Council',
'Bangladesh Space Research and Remote Sensing Organization (SpaRRSO)',
'Bangladesh Standards & Testing Institution',
'Bangladesh Tariff Commission (BTC)',
'Bangladesh Tea Board',
'Bangladesh Telecommunication Regulatory Commission',
'Bangladesh Textile Mills Corporation',
'Bangladesh Tourism Board',
'Bangladesh Unnayan Parishad',
'Banglaesh House Building Finance Corporation',
'BANSDOC',
'Barind Multipurpose Development Authority Bangladesh',
'BIWTA Bangladesh Inland Water Transport Authority',
'Board of Intermediate and Secondary Education, Chittagong',
'Board of Intermediate and Secondary Education, Comilla',
'Board ofIntermediate and Secondary Education, Rajshahi',
'Board of Investment',
'Border Guard Bangladesh (BGB)',
'Bureau of Manpower, Employment and Training (BMET)',
'Bureau of Non-Formal Education (BNFE)',
'Central Extension Resources Development Institute (CERDI)',
'Central Procurement Technical Unit',
'Chittagong City Corporation',
'Chittagong Development Authority (CDA)',
'Chittagong Hill Tracts Development Board',
'Chittagong Port Authority (CPA)',
'Civil Aviation Authority, Bangladesh',
'Civil Suit Management',
'Controller General Defence Finance (CGDF)',
'Copyright Office, Bangladesh',
'Coastal Security in Bangladesh',
'Cotton Development Board',
'Custom House Chittagong',
'Cyclone Preparedness Programme (CPP)',
'Defence Services Command and Staff College',
'Department of Agricultural Extension',
'Department of Agricultural Marketing',
'Department of Cooperatives Bangladesh',
'Department of Environment',
'Department of Fisheries Bangladesh',
'Department of Immigration & Passports',
'Department of Patents, Designs and Trademarks (DPDT)',
'Department of Shipping (DOS)',
'Department Of Social Services (DSS)',
'Department of Textile',
'Department of Youth Development',
'Deputy Commissioner Bandarban',
'Dhaka Metropolitan Police',
'Dhaka North City Corporation',
'Dhaka Transport Coordination Board (DTCB)',
'Director General of Defenece Purchase (DGDP)',
'Directorate General of Drug Administration (DGDA)',
'Directorate General Of Health Service',
'Directorate of Drugs Administration',
'Directorate of Inspection and Audit (DIA)',
'Directorate Of National Savings (DNS)',
'DIRECTORATE OF NURSING SERVICES',
'Economic Relations Division (ERD), Ministry of Finance',
'Education Board Bangladesh',
'E-Government Procurement (E-GP)',
'Energy And Mineral Resources Division (EMRD)',
'Essential Drugs Company Limited - EDCL',
'Export Promotion Bureau',
'Family Planning Division',
'Ministry of Finance',
'Fisheries Research Institute',
'Hydrocarbon Unit',
'Implementation Monitoring and Evaluation Division (IMED)',
'Institute of Public Health Nutrition (IPHN)',
'Internal Resources Division (IRD)',
'Investment Corporation of Bangladesh',
'Khulna City Corporation',
'Law and Justice Division',
'Legal Registrant of Bangladesh',
'Local Governent Division LGRD',
'Military Institute of Science & Technology (MIST)',
'Ministry of Agriculture',
'Ministry of Civil Aviation & Tourism',
'Ministry of Commerce',
'Ministry of Communication',
'Ministry of Cultural Affairs',
'Ministry of Disaster Management and Relief',
'Ministry of Education',
'Ministry of Environment & Forest',
'Ministry of Expatriates Welfare and Overseas Employment',
'Ministry of Fisheries and Livestock',
'Ministry of Foreign Affairs',
'Ministry of Health and Family Welfare',
'Ministry of Home Affairs',
'Ministry of Industries',
'Ministry of Information',
'Ministry of Information & Communication Technology',
'Ministry of Labour and Employment',
'Ministry of Land',
'Ministry of Law, Justice and Parliamentary Affairs',
'Ministry of Liberation War Affairs',
'Ministry of Planning',
'Ministry of Posts and Telecommunications',
'Ministry of Primary & Mass Education',
'Ministry of Railways ',
'Ministry of Religious Affairs',
'Ministry of Shipping & Inland Water Transport',
'Ministry of Social Welfare',
'Ministry of Textile and Jute',
'Ministry of Water Resources',
'Ministry of Youth and Sports',
'National Academy for Educational Management (NAEM)',
'National Academy for Primary Education (NAPE) Bangladesh',
'National Archives Of Bangladesh',
'National Board of Revenue',
'National Book Center Of BANGLADESH',
'National Curriculum & Textbook Board',
'National Housing Authority (NHA) Bangladesh',
'National Institute of Local Government',
'National Library',
'National Museum of Science & Technology (NMST)',
'National Savings',
'NGO Affairs Bureau (NGOAB)',
'Office of the Comptroller and Auditor General of Bangladesh',
'Palli Daridro Bimochon Foundation (PDBF)',
'Pashchimanchal Gas Company Limited',
'Patuakhali Police',
'Planning Division',
'Posts & Telecommunications Division',
'Power Cell, Ministry of Power, Energy and Mineral Resource',
'Power Division',
'Pragoti Industries Limited',
'Primary and Mass Education',
'Public Finance Foundation',
'Public Works Department',
'Rajdhani Unnayan Kortipakkha (RAJUK)',
'Rangamati Hill district',
'Rangpur Municipal',
'Rapid Action Battalion (RAB)',
'Registrar of Joint Stock Companies and Firms',
'Roads & Highways Department RHD',
'Rupantarita Prakritik Gas Company Limited',
'Rural Development & Cooperative Division',
'Rural Power Company Limited',
'Second Urban Primary Health Care Project',
'Secondary Education Quality and Access Enhancement Project (SEQAEP)',
'Seed Certification Agency',
'SICT Ministry Of Planning',
'Small & Medium Enterprise Foundation',
'Supreme Court of Bangladesh',
'Survey of Bangladesh',
'Sylhet City Corporation',
'The Bangladesh Professional Engineers, Registration Board (BPERB)',
'The Bangladesh Rice Foundation (BRF)',
'The Comprehensive Disaster Management Programme (CDMP)',
'The Directorate of Technical Education (DTE)',
'The National Academy for Educational Management (NAEM)',
'The Security Printing Corporation (Bangladesh) Ltd (SPCBL)',
'Titas Gas Transmission and Distribution Company Limited',
'Trading Corporation of Bangladesh (TCB)',
'Urban Community Volunteer',
'Water Resources Planning Organization (WARPO)',
'Golden Harvest Group',
'APS Group',
'Crown Cements',
'Aliance Holdings & 1Asia Alliance Communication',
'CONCORDE Group',
'Danish Dairy Farms Ltd',
'Delsey Cotton Spinning Mills Limited',
'TELE BARTA LIMITED',
'Aman Spinning Mills Ltd',
'Samah Razor Blades Industries Ltd',
'Packman Limited',
'SHOVON GROUP',
'RADIANT AUTOMOATION LTD',
'MONNO CERAMICS',
'Yongtai Industries Bangladesh Ltd',
'PICARD BANGLADESH LIMITED',
'KHADIM CERAMIC WORKS LTD',
'JOHNY TEXTILE MILLS LTD',
'ALLTEX',
'Viquarunnisa Noon School and College',
'PARTEX STAR GROUP',
'ABX LOGISTICS BANGLADESH LTD',
'GSP FINANCE COMPANY (BD) LTD',
'SUN LIFE INSURANCE COMPANY LTD',
'SONALI AANSH INDUSTRIES',
'PARADISE GROUP',
'MINAR INDUSTRIES (PVT) LTD',
'SM GROUP',
'SHINEST GROUP',
'Shepherd Industries Ltd',
'BT Communications Bangladesh Ltd',
'MEL GROUP',
'THE BENGAL PACKAGES',
'Global Capsules Limited',
'Apex Tannery Limited',
'DIPON GROUP',
'NASSA Group',
'Moulana Bhashani Medical College',
'Mahin Group',
'IUBAT',
'Mahin Apparels',
'Convince Apparels',
'Nitol-Niloy Group',
'Unitrend Limited',
'Habib Group',
'Nandan Group',
'European Standard School',
'Ibn Sina Trust',
'Ornate Group',
'Maple Leaf School',
'Mondol Group',
'Aramit Group',
'Fortuna Group',
'Elite Group',
'Radio Today Ltd',
'Delta Hospital',
'East West Medical College',
'Islami Insurance Bangladesh Limited',
'Prime Financial Group',
'Ayurvedic Pharmaceuticals (AP) Ltd',
'Wings Group',
'Dhaka Commerce College',
'Anwar Group',
'A G Automobiles - Concern of Anwar Group',
'MF Consumers Ltd',
'IBAIS University',
'Esquire Knitwear',
'TecAdvantage',
'NR Group ( the Limited Liability Concerns)',
'Gemcon Group',
'The Financial Express',
'Manarat',
'Nuvista Pharma',
'Khaled Group',
'Gokaldas Images (Bangladesh) Private Limited',
'Ananda Shipyard & Shipways Ltd',
'Bangla Lion Communication Ltd',
'Integra Group',
'Saudi Bangladesh Industrial and Agricultural Investment Company',
'HRC Ltd',
'DNS Group',
'Ideal College',
'Midas Financing Limited',
'Milk Vita',
'Central Hospital',
'Kohinoor Chemicals Ltd',
'Tusuka Group',
'National Blind Care Society',
'Agroforestry Improvement Partnership (IC- Leaf project)',
'Keya Group of Industries',
'Holy Family Red Crescent Medical College Hospital',
'BGMEA (including BUFT)',
'Electra Group',
'Limo Electronics Ltd',
'Bashundhara Group',
'University of Liberal Arts Bangladesh (ULAB)',
'Fakir Dye and Chemical',
'Federation of Bangladesh Chamber of Commerce and Industries ( FBCCI )',
'Apex Pharma Ltd',
'Apex Investments Ltd',
'Jayson Pharnaceuticals',
'Bracnet',
'Executive Machines Ltd',
'Fashrobe Garments Ltd',
'Asiatic Talking Point',
'Purbani Group',
'Daily Prothom Alo',
'Chittagong Chamber of Commerce and Industries',
'Daily Inquilab',
'PSSL-FF',
'Free School Street Property Limited',
'Sikomi Properties Limited',
'Pahartali Power House',
'South East Trading Limited',
'Birshrestho Noor Mohammad Public School & College',
'Danish Food Products',
'Danish Milk Bangladesh Ltd',
'Amber Cotton Mills Ltd',
'Amber Pulp and Paper Mills Ltd',
'Danish Distribution Network Ltd',
'Star Vegetable Oil Mills Limited',
'Star Coconut Mills Limited',
'Dhakacom Ltd (ISP)',
'Fotoroma Ltd',
'University of Dhaka',
'Ferrotechnic Limited',
'Hashem Corporation (Pvt) Ltd',
'Radio Dhaka',
'uPVC Pipes & Fittings',
'Hosaf Group',
'Hosaf Metar Industry Ltd',
'Hosaf International Ltd',
'Hosaf Gene Cure Ltd',
'Hosaf Power Generation Co Ltd',
'Diabetic Association of Bangladesh',
'Euro Knitting and Dyeing Ind Ltd',
'East West University EWU)',
'Shamol Bangla Media Ltd (Banglavision)',
'Jahangir and Others',
'Islam Group',
'SAARC Meteorological Research Centre (SMRC)',
'Dhaka City College',
'REHAB',
'BAPEX',
'BKMEA',
'Rahmat Group',
'Medical College for Women & Hospital',
'Popular Group',
'Hamdard Labratories',
'Bangladesh Institute of International and Strategic Studies',
'Bangladesh Erectors Limited',
'Bangladesh Manabadhikar Bastabayan Sangstha:',
'ICMAB-The Institute of Cost and Management Accountants of Bangladesh:',
'Channel 24',
'Ekattor TV',
'Anjuman Mufidul Islam',
'Swanirvar Bangladesh',
'Dhaka Residential Model College',
'Birshrestha Munshi Abdur Rouf Public College',
'Infrastructure Investment Facilitation Centre',
'Rural Electrification Board',
'Comprehensive Holdings',
'Bangladesh Football federation',
'Tele-Talk',
'Institute of Chartered Accountant of Bangladesh (ICAB)',
'SME Foundation',
'Bangladesh Open University',
'West Zone Power Distribution Company Limited',
'Dhaka Dental College and Hospital',
'NEW AGE GROUP',
'KAI Bangladesh Aluminium Limited',
'QC Corporation Ltd',
'Credit Rating Agency of Bangladesh',
'Grameen Danone Foods Ltd',
'Ananda Group',
'Bangladesh Petroleum Institute',
'Sikder Group',
'Vision Group',
'ELECTION COMMISSION',
'Pendekar Energy (Powertek)',
'BRB Group',
'Eur Service (Bd) Ltd',
'That\'S It Sportswear Limited',
'TK Group of Industries',
'Bangla Trac Communication Ltd',
'Shin Shin Group',
'Viyellatex Group',
'Akij Group',
'Armana Group',
'Well Group',
'HMCL NILOY BANGLADESH LIMITED',
'PRAN RFL Group',
'SINHA GROUP',
'M M ISPAHANI LTD',
'ENERGYPAC',
'SQUARE GROUP',
'Pacific Jeans Ltd (Pacific Group)',
'KDS Group',
'ABC Group:',
'Hamid Group',
'Abul Khair Group',
'Naheed Composite Textile Mills Limited',
'Naheed Cotton Mills Limited',
'JEACON GRAMENTS',
'INTERNATIONAL OFFICE EQUIPMENT (IOE)',
'PRINT PACK INSDUTRIES LTD',
'Blossom Textiles Limited',
'Bombay sweets and Co Ltd',
'Hin Getah Bangladesh Limited',
'GLOBAL BEVERAGE CO LTD',
'ACME GROUP',
'SHAH CEMENT INDUSTRIES LTD',
'APEX GROUP',
'International Leasing & Financial Services Ltd',
'RAHIMAFROOZ',
'Global Heavy Chemicals limited',
'QC CONTAINER LINES',
'Famous Printing and Packaging Ltd',
'K Line Bangladesh Ltd',
'AEG Engineering Ltd',
'Mutual Milk Products/Mutual Food Products Limited',
'Jenny\'s Footwear Limited',
'REGENSEA LINES LTD',
'SEACOM SHIPPING LTD',
'EVERBEST SHIPPING AGENCIES LTD',
'Hussain Trading Co',
'R B Group',
'Aamra Companies',
'National Life Insurance',
'Dekko Group',
'AK KHAN & COLIMITED',
'PACIFIC MOTORS LIMITED',
'Unique Group',
'MJL BANGLADESH LTD',
'Noman Group',
'Asiatic Marketing Ltd',
'United Group',
'Envoy Group',
'Apex Adelchi Footwear Limited',
'Uttara Group',
'Bangladesh Shipping Corporation',
'Kalpataru Power Transmission Limited',
'USTC',
'Titas Sportswear Industries Ltd',
'Lalmai Sportswear Industries Ltd',
'Karnaphuli Steel Milss Ltd',
'Aftab Group',
'Dhaka Stock Exchange',
'TVS Auto Bangladesh Limited',
'MGH Holdings Ltd',
'Chittagong Jute Manufacturing Co Ltd',
'Nasirabad Properties Limited',
'Energyprima Ltd',
'CDBL (Central Depository Bangladesh Limited)',
'CityGroup',
'ICB',
'Globe Travel Distributions Bangla Pvt Ltd/Amadeus',
'BANGLADESH INTERNATIONAL TUTORIAL',
'BSA Group of Companies',
'STRUCTURED DATA SYSTEMS LIMITED',
'Kumudini Welfare Trust of Bengal (BD)',
'CORR-The Jute Works',
'AMTOB (ASSOCIATION OF MOBILE OPERATORS OF BD) TRUST',
'UNION GROUP',
'Summit Group',
'GONO SHAKKHARATA OVIJAN/CAMPAIGN FOR POPULAR EDUCATION (CAMPE)',
'HKD International',
'FASHIONIT COMPANY LIMITED',
'Shun Shing Group',
'Rahman Rahman Huq (KPMG)',
'Confidence Group',
'Paragon Feed Ltd',
'Paragon Poultry Ltd',
'IMPACT FOUNDATION BANGLADESH',
'Orient Energy Systems Ltd',
'UniHealth Manufactureres Ltd-BC',
'PADMA GROUP OF CONVERTERS',
'Al-Karim Paints and Chemicals Ltd',
'Karnaphuli Group',
'Baizid Steels Ltd',
'CIRDAP',
'Genetic Limited',
'Mirpur Ceramics Works',
'UTAH GROUP',
'Evince Group',
'Meghna Group of Industries (MGI)',
'TMSS',
'Interspeed',
'SOORTY TEXTILE (BD) LIMITED',
'OPEX GROUP/SINHA GROUP',
'Sinha Medlar Group',
'US Bangla Group',
'MAX Group',
'Fullcharm Fashion Knitters Ltd',
'Good Times Holding Limited',
'AB Bank Limited',
'ACI Limited',
'Aman Cotton Fibrous Limited',
'Advent Pharma Limited',
'Apex Holdings Limited',
'Apex Group',
'Baraka Power Limited',
'BATA',
'BRITISH AMERICANN TOBACOO(BD) LTD',
'Bangladesh Building Systems Ltd (BBS)',
'Bangladesh Finance Limited',
'BERGER PAINTS BD LTD',
'Beximco Group',
'AFC Agro Biotech Limited',
'Aftab Automobiles Limited',
'Alif Industries Limited',
'Aman Feed Limited',
'Ambee Pharmaceuticals Limited',
'Anwar Galvanizing Limited',
'Asian Tiger Sandhani Life Growth Fund',
'Bangas Limited',
'Bangladesh Autocars Limited',
'BDCOM CONNECTING PROGRESS',
'Bangladesh Submarine Cable Company Limited',
'Central Insurance Company Limited',
'The City Bank',
'Coppertech Industries Limited',
'DELTA BRAC HOUSING CORPORATION LTD',
'Delta Life Insurance',
'Dhaka Insurance Ltd',
'Desh Garments Limited',
'Dragon Sweater & Spinning Limited',
'Eastern Insurance Company Limited',
'Eastland Insurance Company Limited',
'Eastern Lubricants Limited',
'Esquire Knit Composite Limited',
'Far East Knitting and Dyeing Industries Limited',
'GBB Power Limited',
'UNILEVER CONSUMER CARE LIMITED',
'GRAMEEN PHONE LTD',
'GPH ISPAT LTD',
'GREEN DELTA INSURANCE',
'HEIDELBERG CEMENT/SCAN CEMENT BD LTD',
'PRIDE GROUP',
'IDLC',
'IT CONSULTANTS LIMITED',
'Janata Insurance Ltd',
'JMI Syringes & Medical Devices Limited',
'Khulna Power Distribution Company',
'Lanka Bangla',
'LAFARGE HOLCIM BANGLADESH LTD',
'Libra Infusions Limited',
'Linde Bangladesh limited ( former BOC Bangladesh Limited )',
'L R Global',
'Malek Spinning Mills Ltd',
'MARICO BANGLADESH LIMITED',
'DBL Group',
'MEGHNA CEMENT',
'Mercantile Bank',
'M I Cement',
'Mobil Jamuna lubricant Ltd',
'NAVANA LIMITED',
'New Line Clothings Ltd',
'Olympic Industries',
'Phoenix Group ( Phoenix Finance , Phoenix Securities, Phoenix Insurance )',
'PRAGATI INSURANCE LIMITED',
'Premier Cement',
'Prime Insurance',
'Progressive Life Insurance Company Ltd',
'Paramount Textile Limited',
'Quasem Group (Quasem Industries Limited, Quasem Lamps Ltd, Quasem Foods Ltd, Quasem Foundation)',
'Queen South Textiles Ltd',
'Rahim Textiles Mills',
'RECKITT BENCKISER',
'RENATA LTD',
'Republic Insurance Company',
'Ring Shine Textiles Ltd',
'Ratanpur Steel Re-Rolling Mils Ltd (RSRM)',
'Runner Group',
'SAIF Powertec Limited',
'MH Samorita Medical College & Hospital',
'Shasha Denims Ltd',
'Shurwid Industries',
'SINGER BANGLADESH LTD',
'Sino Bangla Industries Ltd',
'Standard Insurance Limited',
'Stylecraft Limited',
'Trust Bank Limited',
'United Finance Limited',
'UTTARA BANK LIMITED',
'Western Marine Group',
'Active Fine Chemical Ltd',
'AGNI SYSTEMS LIMITED',
'Agrani Insurance Ltd',
'Aziz Pipes Limited',
'Central Pharmaceuticals Ltd',
'FU-WANG CERAMIC INDUSTRY LIMITED',
'Fu-Wang Foods Ltd',
'Information Service Network (ISN)',
'Makson Group',
'Mercantile Insurance Company',
'Miracle Industries Ltd',
'Prime Textile Spinning Mills Ltd',
'Zahintex Ltd',
'Far Chemical Industries Limited',
'First Bangladesh Fixed Income Fund',
'Fortune Shoes Limited',
'Gemini Sea Food Limited',
'Genex Infosys Limited',
'GQ Ball Pen Industries Limited',
'Grameen One : Scheme Two',
'HWA Well Textiles (BD) Limited',
'Intraco Refueling Station Limited',
'IPDC Finance Limited',
'Islamic Insurance Bangladesh Limited',
'Jamuna Oil Company Limited',
'Karnaphuli Insurance Company Limited',
'Kattali Textile Limited',
'M L Dyeing Limited',
'Monno Jute Staffers Limited',
'Nahee Group',
'Nitol Insurance Company Limited',
'Northern Jute Manufacturing Company Limited',
'Northern Islami Insurance Limited',
'National Tea Company Limited',
'National Tubes Limited',
'Nurani Dyeing & Sweater Limited',
'Oimex Electrode Limited',
'Pacific Denims Limited',
'Pharma Aids',
'Pragati Life Insurance Company Limited',
'Purabi Gen Insurance Company Limited',
'Renwick Jajneswar & Company (BD) Limited',
'Saiham Cotton Mills Limited',
'Saiham Textile Mills Limited',
'Sandhani Life Insurance Company Limited',
'Silco Pharmaceuticals Limited',
'Simtex Industries Limited',
'SK Trims & Industries Limited',
'Sonar Bangla Insurance Limited',
'Shahjibazar Power Company Limited',
'S S Steel Limited',
'Takaful Islami Insurance Limited',
'Vanguard AML BD Finance',
'VF Thread Dyeing Limited',
'Wata Chemicals Limited',
'Anlimayam Dyeing Limited',
'Atlas Bangladesh Limited',
'City General Insurance Company Limited',
'CVO Petrochemical Refinery Limited',
'Deshbandhu Polymer',
'Eastern Cables Limited',
'Fine Foods Limited',
'Hakkani Pulp & Paper Mills Limited',
'Kay & Que Bangladesh Limited',
'Khan Brothers PP Woven Bag Industries Limited',
'Legacy Footwear Limited',
'Mozaffar Hossain Spinning Mills Limited',
'Olympic Accessories Limited',
'Paramount Insurance Company Limited',
'Peoples Insurance Company Limited',
'Rangpur Dairy & Food Products',
'Safko Spinning Mills Limited',
'Salvo Chemical Industry Limited',
'Samata Leather Complex Limited',
'Sonargaon Textiles Limited',
'Shinepukur Ceramics Limited',
'Tosrifa Industries Limited',
'Yeakin Polymer Limited',
'Zaheen Spinning Limited',
'Bangladesh Krishi Bank',
'Prime Asset Group',
'China Petroleum Pipeline Engineering Company Limited',
'Therap BD',
'Ahsania Mission',
'Amanat Shah Group',
'Community Bank Bangladesh Limited',
'Modhumoti Bank Limited',
'PHARMA SOLUTIONS BANGLADESH LIMITED ',
'TECH VALLEY COMPUTERS LTD',
'PHP Group',
'National Polymer Industries Ltd',
'MGH GROUP',
'Edcon International (Singapore) PTE LTD',
'SITA Information Networking Computing BV',
'Thakral Information Systems Private Ltd',
'Co water International',
'NATIONAL DEMOCRATIC INSTT (NDI)',
'HAREWELLE INTERNATIONAL LIMITED',
'CNFA',
'ADD International - Action on Disability and Development',
'IFDC',
'QUALITY PAPER MILL LTD',
'PDS Multinational / Deepak Seth Group',
'Simba Fashions Limited',
'Continental Insurance Company Limited',
'ASIA INSURANCE LIMITED',
'Hamid Fabrics Ltd',
'METRONET BANGLADESH LTD',
'Beacon Pharmaceuticals',
'RRM Group',
'Asian Disaster Preparedness Centre',
'Butterfly Marketting Limited',
'Standard Asiatic Oil Company',
'Asia Energy Corporation (Bangladesh) PTY Ltd',
'NDB Capital',
'Hamid Group (Garments)',
'Arannayk Foundation',
'Dada Group',
'GOODMAN COMPANY LIMITED',
'Independent TV',
'JOHN SNOW INC (JSI)',
'SOUTH ASIA PARTNERSHIP BANGLADESH',
'SWISS COLOURS BANGLADESH LIMITED',
'Embassy of Maldives -HIGH COMMISSION OF THE REPUBLIC OF MALDIVES',
'UNITED DEVELOPMENT INITIATIVES FOR PROGRAMMED ACTIONS',
'INTERNATIONAL JUTE STUDY GROUP',
'ORASINVEST (BANGLADESH) LTD',
'Haddad Organization',
'China National Electrical Wire Company',
'IBM Bangladesh',
'Concern Universal',
'Isolux Corsan/Isolux Ingenieria SA',
'Project Concern International',
'Ajinomoto Bangladesh',
'PROGRAM SUPPORT UNIT/CIDA',
'Alifia Properties Ltd-CIC',
'ARD, INC',
'CEMEX CEMENT BANGLADESH LTD',
'PEL BANGLADESH SERVICES LIMITED',
'Eastern Atlas Ltd',
'AUTOMATION ENGINEERING AND CONTROLS LTD',
'MEDICO Sports Fashion GmbH',
'Ahead Logistics',
'Always on Network Bangladesh',
'Gram Unnyan Karma',
'Indesore Group',
'Centre for Development Services',
'Origin Logistics',
'Kemiko Pharmaceuticals Limited',
'Pharaoh Communications Ltd',
'Nagar Homes',
'Kaltimex Energy Bangladesh (Pvt) Ltd',
'Intramex Group',
'Eon Animal Health Products Limited -EB',
'A-One BD Limited',
'Junior Laboratory (PVT) Ltd',
'THE DATABIZ SOFTWARE LTD',
'Advanced ERP (BD) Ltd',
'Bangladesh Institute of Labour Studies',
'Bestec Group',
'Interspeed -BC',
'HB CONSALTANTS LTD',
'Signage Group',
'ASSURANCE MONI GROUP',
'Handicap International',
'Danchurch Aid (DCA)',
'CodeMate',
'Mothercare Sourcing Division Bangladesh',
'MNC Apparels Ltd',
'Dynasty Group Ltd',
'Grabal Alok (UK) Limited',
'NOKON Ltd',
'Panache Knitted Creations Ltd',
'Toy Woods (BD) Co Ltd',
'CONVEYOR LOGISTICS LTD',
'METRO MAKERS AND DEVELOPERS LTD',
'Building Technology and Ideas-BC',
'Foreign Investors Chamber of Commerce and Industries -BC',
'Brainchild Communication Bangladesh Limited',
'BURO BANGLADESH',
'Spectrum Lanka Technology Solutions Ltd',
'SMCC-ITD JV',
'W3 ENGINEERS LTD',
'University of Asia Pacific Banglades (UAP)',
'BRAC University (BRAC)',
'ASA University Bangladesh (ASAUB)',
'Atish Dipankar University of Science and Technology (ADUST)',
'Shanto-Mariam University of Creative Technology (SMUCT)',
'Eastern University Bangladesh (EUB)',
'State University Of Bangladesh (SUB)',
'Stamford University Bangladesh (SU)',
'International University of Business Agriculture & Technology (IUBAT)',
'American International University Bangladesh (AIUB)',
'Ahsanullah University of Technology (AUST)',
'United International University (UIU)',
'Bangladesh University of Business & Technology (BUBT)',
'University of Development Alternative (UODA)',
'Southeast University (SEU)',
'Groz-Beckert',
'E Courier Limited',
'Noman Group / Saad Group',
'BAF Shaheen English Medium School',
'BIMS',
'Hurdco International School',
'International Hope School Bangladesh',
'Manarat Dhaka International School and College',
'Oxford International School',
'Playpen School',
'SCHOLARS INTERNATIONAL SCHOOL',
'Singapore International School',
'Sir John Wilson School',
'SOUTH BREEZE SCHOOL',
'Sunbeams School',
'Sunnydale School',
'Sunshine Grammer School',
'Australian International School',
'International School Dhaka',
'Cardiff International School Dhaka (CISD)',
'Daffodil International School',
'European Grammar School',
'Yale International School',
'SALVATION INTERNATIONAL SCHOOL AND COLLEGE',
'ASA',
'Ridoy Rifat Industries Ltd',
'Swiss Bio hygienic Equipment Ltd',
'Dhaka Shishu Hospital',
'FIELD INFORMATION SOLUTIONS LTD',
'TEEN AGE MODERN FASHION LTD',
'DHAKA INTERNATIONAL UNIVERSITY',
'HOLY SYLHET HOLDINGS LTD',
'ADC',
'Crown Exclusive Wears Ltd.',
'KAZI AGRO LTD',
'UTTARA CRESENT CLINIC LTD',
'RAINBOW LOGISTICS LTD',
'HAQUE',
'SALAM STEEL CONCAST RE-ROLLING MILLS LTD',
'MODE MAKERS',
'Designer Fashion Ltd',
'DEKKO LEGACY GROUP (RMG)',
'DARAZ BANGLADESH LTD',
'ORIENT ALLURE KNITWEAR LTD',
'BENGAL BEE LTD',
'MADINA POLY FIBRE LTD',
'NET 71',
'RADIANT AVIATION',
'NATIONAL CREDIT RATINGS LTD',
'BEST SHIRTS LTD',
'ARCOBALENO FOOTWEAR LTD',
'BRIGHT RIVER BANGLADESH LTD',
'ASIATIC SOCIETY OF BANGLADESH',
'GREENLAND PHARMACEUTICALS LTD',
'CRAFTSMEN LTD',
'ZASS Telecom LTD',
'NORBAN COMTEX LIMITED',
'JOYCALLS BANGLADESH LTD',
'AJI GROUP',
'TUNIC APPARELS LTD',
'VERSATILE CEATION LTD',
'A K KHAN & COMPANY LTD',
'COAL POWER GENERATION COMPANY BANGLADESH',
'MGH Group',
'Robert Bosch (Bangladesh) Ltd ',
'Nippon Paint (Bangladesh) Private Ltd ',
'KYCR COIL INDUSTRIES LIMITED',
'Dhaka South City Corporation',
'Disabled Rehabilitation and Research Association (DRRA)',
'X SOLUTIONS LTD',
'CONCRETE & STEEL TECHNOLOGIES LTD',
'ABANTI COLOR TEX LTD',
'AMBER DENIM MILLS LTD',
'HELLENIC SOURCING HONG KONG LTD',
'MY SOFT LTD',
'SYLHET WOMEN\'S MEDICAL COLLEGE HOSPITAL',
'METROCEM',
'ADN TECHNOLOGY',
'WEBLINK COMMUNICATION LTD',
'FILAMENT ENGINEERING LTD',
'AVENUE TRADE & ENGINEERING',
'SURJER HASHI NETWORK',
'LUB RREF BD LTD',
'YANGMING HANHAI (BANGLADESH) LTD',
'SIGNIFY BANGLADESH LTD',
'JUST JAMES BD LTD',
'CG APPAREL LTD',
'ALIF EMBROIDERY VILLAGE LTD',
'GANA UNNAYAN KENDRA',
'QUICKLY GLOBAL LTD',
'DESIGN ACE LTD',
'EON FOOD LTD',
'TIFFIN BOX LIMITED',
'DENIM FASHION LTD',
'AMAN CEMENT MILLS UNIT-2 LTD',
'AMAN GROUP',
'DYSIN GROUP',
'CONCITO PR (PVT) LTD',
'GARAN MANUFACTURING CORPORATION',
'NIPPON PAINT (BANGLADESH) PRIVATE LTD',
'EURO PHARMA LTD',
'RISHAL GARMENTS LTD',
'IDS Group',
'Kona Software Lab Limited',
'NORTH WEST POWER GENERATION COMPANY LTD',
'Global Alliance for Improved Nutrition ',
'AGRANI BANK ',
'JANATA BANK LIMITED',
'JAMUNA GROUP',
'Dhaka Cantonment Girls\' Public School and College',
'Savoy Ice Cream Factory Ltd',
'ACI GROUP',
'MULTIFABS LIMITED',
'Bengal Commercial Bank',
'SHIMANTO BANK LIMITED',
'HAMEEM GROUP',
'New Star Hilon Co Ltd',
'ANANTA APPARELS LIMITED',
'ADCOMM LTD',
'SQ Group',
'Veritas Pharmaceuticals Limited',
'Research, Training and Management International',
'Partex / Amber Group ',
'Bengal Communication Limited',
'Crystal Group CRYSTAL CARS',
'Adobe Builders Ltd',
'Meghna Bank',
'BIAM MODEL SCHOOL & COLLEGE',
'Institute of Water Modelling',
'SARA LIFESTYLE LTD',
'First Security Islami Bank Limited (FSIBL)',
'NRB COMMERCIAL BANK LIMITED',
'Bangladesh International School and College',
'Bproperty',
'Silver Line Composite Textile',
'Pretty Group',
'GUARDIAN LIFE INSURANCE LIMITED',
'Louietex',
'Aparajeyo Bangladesh',
'Epic Group',
'Embassy of Indonesia',
'UCEP - Bangladesh',
'Agricultural Extension Component (AEC)',
'ZTE CORPORATION (BD OFFICE)',
'Unimed & UniHealth Manufacturers Ltd',
'Sir William Beveridge Foundation',
'Echotex',
'Fiber @ Home',
'Shakti Foundation',
'Mennonite Central Committee (MCC)',
'Muslim Aid - UK',
'Patenga Footwear (Pvt) Limited',
'Matador',
'FU WANG GROUP',
'Nourish Agro Ltd',
'Sheltech (PVT) Ltd',
'Impress Group (Channel I)',
'Palmal Group',
'NTV',
'Willes Little Flower School',
'Building For Future',
'Lab Aid Group',
'Oriental Real Estate',
'Fakir Knitwear',
'The Daily Samakal',
'Islami Bank Foundation',
'FAKIR FASHION',
'Rupayan Group',
'Islamic Bank Foundation Group',
'Meghna Group',
'Broad Band Telecom Services Limited',
'EXIM Bank Hospital',
'Star Particle Board Mills Ltd',
'Chittagong Grammer School',
'Jalalabad Ragib Rabea Medical College and Hospital',
'Bangladesh Sangbad Santha',
'Islamic Foundation',
'Crony Group',
'Premier Leasing and Finance Limited',
'Fashion Product Group',
'Midland Bank',
'Farmer\'s Bank',
'Grameen Knitwear',
'International Islamic University Chittagong',
'Ranks ITT',
'Kuwait Embassy',
'GERAMAN TECHNICAL COOPERATION',
'COVANTA BANGLADESH OPERATING LTD',
'Clariant (Bangladesh) Ltd',
'Halcrow Bangladesh Limited',
'Smiling Sun Franchise Program',
'GEC',
'Niko Resources (Bangladesh) Limited',
'ThyssenKrupp Elevator (BD) Pvt Ltd',
'Eltek Valere',
'GTL',
'Youn An Hat Bangladesh',
'CMA CGM Bangladesh Shipping Ltd',
'TNT Express',
'Young An Hat',
'Dascher',
'TKM Global',
'Areva T & D',
'Marks & Spencer',
'Dun & Bradstreet Rating Agency Bangladesh/Dun and Bradstreet',
'Target Sourcing Services/AMS',
'Newtimes Group',
'ITC Logistics',
'Agreeya Solutiions',
'GroupeCarrefour',
'DAI',
'Dachser',
'HelpAge International (HAI) Bangladesh',
'Education and Development Foundation-Educo',
'Alcatel Lucent',
'Thomson Reuters',
'Crystal Martin Holdings Ltd',
'Union de Banques Arabes et Francaises (UBAF)',
'Fael Khaer Program (IDB)',
'The Islamic Corporation for the Insurance of Investment and Export Credit (IDB)',
'Mott MacDonald (Group as a whole and the concerns)',
'Saudi Bangladesh Investment Company',
'Medicins Sans Frontier / Dotors without Border',
'ESCENIC ASIA',
'Sun Fortune Limited',
'USC CANADA BANGLADESH',
'Regent Global Sourcing',
'Augere Bangladesh Ltd',
'Aramex',
'Daewoo International Corporation',
'Western Union Money Exchange',
'Hanjing Shipping',
'Silvia ShipTrade',
'Hewlett Packard',
'Polyconcept Group',
'Mission Aviation Fellowship (MAF) -Sweden',
'ICICI Bank Representative Office',
'ITS: International Turnkey Systems',
'Starship Maritime',
'Partners in Health and Development',
'Pulcra Chemicals Limited',
'Rohto-Mentholatum (Bangladesh) Limited:  ',
'Ogilvy Mather',
'Checkpoint Systems Bangladesh Limited',
'International Network of Alternative Financial Institutions',
'ACCA',
'BSI Inspectorate',
'Action for Enterprises Limited',
'The Children\'s Place',
'Good Neighbour',
'Mashreq Bank',
'Benetton Asia Pacific Ltd',
'LG Electronics Singapore Pte Limited:',
'Orbis International',
'Canadian International Developement',
'German Technical Cooperation',
'QUBEE',
'Microsoft Bangladesh Limited',
'Elanco Bangladesh Limited',
'GENESIS DENIM LIMITED',
'Hkd Outdoor Innovations Limited',
'Lava International (Bangladesh) limited',
'Axis Bank',
'Chittagong Power Company Limited',
'International Air Transport Association (IATA)',
'IUB (Independent University Bangladesh)',
'AK Khan & Co Ltd',
'ASA INTERNATIONAL',
'SUPER REFINERY (PVT) LIMITED',
'Brac Bank Limited',
'EXCEL TELE-COM (PVT) LTD',
'SIEMENS BD LIMITED',
'MOTOROLA TELECOMMUNICATIONS BANGLADESH PVT LTD',
'SEARS Holding Global Sourcing',
'UPS SCS BD LTD',
'Finlay Limited',
'National Bank of Pakistan',
'United Bank of India',
'Embassy of Brazil',
'Embassy of Russia',
'DNV GL BANGLADESH LIMITED (Previously known as GERMANISCHER LLOYD BANGLADESH LTD)',
'Vertive (Bangladesh) PVT LTD',
'SWISS DEVELOPMENT COOPERATION',
'The Micronutrient Initiative / Nutrition International',
'Wells Fargo Bank N A representative office',
'Royal Embassy of Saudi Arabia',
'Weatherford',
'Caritas Bangladesh',
'Habib Bank AG Zurich Representative Office',
'Production Services Network',
'Schlumberger Limited',
'Kerry Logistics',
'Lepra Bangladesh',
'Bharat Heavy Electricals Ltd (BHEL)',
'Swiss Red Cross',
'General Electric International',
'KEC International Limited',
'Geokinetics Ltd',
'LI & FUNG (BANGLADESH) LIMITED',
'Intercontinental Hotel',
'Nour Bangla/ Munir Sulhtian International Ltd',
'Stromme Foundation',
'British Broadcasting Corporation (BBC)',
'BJ Services Company Middle East Ltd',
'Four H Group',
'CLASSNK (Nippon Kaiji Kyokai)',
'Expo Group',
'Incepta Herbal & Nutricare Ltd',
'Premier University',
'Bangladesh Pou Hung Industrial Ltd',
'The Himalaya Drug Company Ltd',
'The Doha Bank',
'JAMUNA SPACETECH JOINT VENTURE LIMITED',
'Gulf Oil Bangladesh Limited',
'AS Bangladesh',
'Enfants Du Monde',
'Solar Electro Bangladesh Ltd',
'OBAYASHI Corporation',
'Alcon Pharmaceuticals Limited',
'Eptisa',
'Chrom World',
'IC Net Limited',
'Quest Holdings Bangladesh Pvt Ltd',
'CBM (Christian Blind Mission)',
'Nagad (Third Wave Technologies Limited)',
'Fuwang Polymer Industry Limited',
'JSC Institute ORGENERGOSTROY',
'JHPIEGO',
'KR Group',
'SMART TECHNOLOGIES BD LTD',
'SNOWTEX SPORTSWEAR LTD',
'Catholic Relief Services',
'F5 Networks Bangladesh Ltd',
'French Development Agency (FDA)',
'Ecorys UK Limited',
'Think Well',
'Fonterra',
'E-VALYCOM LIMITED',
'Sharif Group',
'Intelligent Label Solutions',
'Taskeater Bangladesh Limited',
'UCBL Group',
'Directorate of Secondary & Higher Education (Govt Org)',
'Banga Plastic International Ltd',
'ACME Group',
'Syngenta Bangladesh',
'Danish Refugee Council',
'First Janata Bank',
'URMI Group',
'Manarat International University (MIU)',
'BJIT Limited',
'FORTIS GROUP',
'SPECIAL SECURITY FORCE ']
let temp = []
companyName.map((item,key) => {
    let xx = {
        title:item,
        value:key
    }
    temp.push(xx)
})

export {companyName}


